# Generated by Django 5.2.3 on 2026-08-04 05:56

import django.db.models.deletion
import emailagent.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAgentSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.CharField(blank=True, default='', max_length=32)),
                ('last_synced_internal_date', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sender', models.CharField(max_length=320)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_recipients', models.JSONField(blank=True, default=list)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('bcc_recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_headers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Classification'), ('rfq', 'RFQ / Enquiry'), ('not_relevant', 'Not Relevant'), ('needs_review', 'Needs Manual Review')], db_index=True, default='pending', max_length=20)),
                ('classification_category', models.CharField(blank=True, default='', max_length=20)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('classification_reasoning', models.TextField(blank=True, default='')),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('classification_model', models.CharField(blank=True, default='', max_length=60)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailagent_confirmed_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_attachment_id', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=emailagent.models.email_attachment_path)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('included_in_classification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracked_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
