# Generated by Django 5.2.3 on 2026-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='gmail_attachment_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
