# Generated by Django 5.2.3 on 2026-08-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0002_alter_emailattachment_gmail_attachment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tracked_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
