# Generated by Django 5.2.3 on 2026-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0003_enquiryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
