# Generated by Django 5.2.3 on 2026-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0004_enquiryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='notes',
            field=models.CharField(blank=True, default='', help_text="e.g. 'revised from 3 to 2 on 25 Jul' -- set when the thread shows the client changing a previously requested value, so the reason isn't hidden.", max_length=255),
        ),
    ]
