# Generated by Django 5.2.3 on 2026-08-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0005_enquiryitem_notes'),
        ('so', '0112_add_discount_actions_to_quotationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='match_notes',
            field=models.CharField(blank=True, default='', help_text="Agent's note on the match, e.g. 'no confident catalog match' or 'brand differs from what was requested'.", max_length=255),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='matched_item',
            field=models.ForeignKey(blank=True, help_text="Agent's best catalog match for this requirement line, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.items'),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='matched_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='matched_unit',
            field=models.CharField(blank=True, default='pcs', help_text="Normalized to the quotation form's unit choices (pcs/ctn/roll) -- `unit` above keeps the original text as extracted from the email.", max_length=20),
        ),
        migrations.CreateModel(
            name='QuotationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Drafting'), ('ready', 'Ready for Review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('customer_guess', models.CharField(blank=True, default='', help_text='Best-guess display name, used when there is no confident customer match (quoted as a walk-in/CASH customer under this name).', max_length=255)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_customer', models.ForeignKey(blank=True, help_text="Agent's best match against existing customers, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.customer')),
                ('quotation', models.ForeignKey(blank=True, help_text='Set once a reviewer confirms this draft into a real quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.quotation')),
                ('tracked_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_draft', to='emailagent.trackedemail')),
            ],
        ),
    ]
