# Generated by Django 5.2.3 on 2026-08-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0006_enquiryitem_match_notes_enquiryitem_matched_item_and_more'),
        ('so', '0112_add_discount_actions_to_quotationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdraft',
            name='quotation',
            field=models.OneToOneField(blank=True, help_text='The quotation this draft was automatically turned into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_draft', to='so.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'Drafting'), ('ready', 'Ready for Review'), ('confirmed', 'Quotation Created'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
