# Generated by Django 5.2.3 on 2026-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0007_alter_quotationdraft_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='matched_quantity',
            field=models.IntegerField(blank=True, help_text="Actual quantity quoted, in matched_unit's units -- may differ from `quantity` above when the customer's requested unit was a length measure (e.g. METERS) that had to be converted to whole pieces/rolls against the catalog item's per-unit length.", null=True),
        ),
    ]
