# Generated by Django 5.2.3 on 2026-08-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0008_enquiryitem_matched_quantity'),
        ('so', '0113_quotation_emailed_at_quotation_emailed_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('classify_email', 'Email Classification'), ('draft_quotation', 'Quotation Drafting'), ('rematch_unmatched_items', 'Unmatched Item Rematch'), ('recheck_item_brand_matches', 'Brand Match Recheck')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('flagged', 'Flagged'), ('failed', 'Failed')], db_index=True, default='success', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('issues', models.JSONField(blank=True, default=list, help_text='Human-readable things worth double-checking, e.g. a unit conversion or a low-confidence match. Purely informational -- nothing here has been auto-corrected.')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='so.quotation')),
                ('tracked_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
