# Generated by Django 5.2.3 on 2026-08-11 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0009_agentrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
