# Generated by Django 5.2.3 on 2026-08-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0010_alter_agentrun_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='agent_name',
            field=models.CharField(choices=[('classify_email', 'Email Classification'), ('draft_quotation', 'Quotation Drafting'), ('rematch_unmatched_items', 'Unmatched Item Rematch'), ('recheck_item_brand_matches', 'Brand Match Recheck'), ('send_quotation_email', 'Quotation Sent to Client')], db_index=True, max_length=40),
        ),
    ]
