# Generated by Django 5.2.3 on 2026-08-13 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0011_alter_agentrun_agent_name'),
        ('so', '0113_quotation_emailed_at_quotation_emailed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdraft',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text="Set (instead of `quotation`) when this email was a same-thread follow-up whose changes were merged into an earlier email's quotation rather than creating a second one for the same enquiry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_drafts', to='so.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'Drafting'), ('ready', 'Ready for Review'), ('confirmed', 'Quotation Created'), ('failed', 'Failed'), ('merged', 'Merged into earlier quotation')], db_index=True, default='pending', max_length=20),
        ),
    ]
