# Generated by Django 5.2.3 on 2026-08-22 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0012_quotationdraft_merged_into_and_more'),
        ('so', '0114_quotation_emailed_message_id'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='submittal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='submittal.submittal'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_name',
            field=models.CharField(choices=[('classify_email', 'Email Classification'), ('draft_quotation', 'Quotation Drafting'), ('rematch_unmatched_items', 'Unmatched Item Rematch'), ('recheck_item_brand_matches', 'Brand Match Recheck'), ('send_quotation_email', 'Quotation Sent to Client'), ('draft_submittal', 'Submittal Drafting'), ('send_submittal_email', 'Submittal Sent to Client')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SubmittalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Drafting'), ('ready', 'Ready for Review'), ('confirmed', 'Submittal Created'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_brand', models.ForeignKey(blank=True, help_text="Agent's best match for which catalog brand this submittal is for.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittalbrand')),
                ('source_quotation', models.ForeignKey(blank=True, help_text="The quotation this draft was generated from, if triggered via 'Generate Submittal' rather than an email.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.quotation')),
                ('submittal', models.OneToOneField(blank=True, help_text='The submittal this draft was automatically turned into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_record', to='submittal.submittal')),
                ('tracked_email', models.OneToOneField(blank=True, help_text='The email that asked for a material submittal, if this draft came from an email rather than an existing quotation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submittal_draft', to='emailagent.trackedemail')),
            ],
        ),
    ]
