# Generated by Django 5.2.3 on 2026-08-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0013_agentrun_submittal_alter_agentrun_agent_name_and_more'),
        ('so', '0114_quotation_emailed_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='source_attachment',
            field=models.CharField(blank=True, default='', help_text="Which attachment (filename) or part of the email this item came from -- set by the classifier when the RFQ has more than one client_requirement attachment (e.g. two separate BOQs for two different buildings). Blank when there's only one requirement source (the common case) or the item came from the email body. Used by draft_quotation() to draft a SEPARATE quotation per distinct attachment instead of merging unrelated scopes into one -- see quotation_agent._group_items_by_scope.", max_length=255),
        ),
        migrations.CreateModel(
            name='AdditionalQuotationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_attachment', models.CharField(blank=True, default='', help_text='Which attachment/scope this quotation was drafted from (matches EnquiryItem.source_attachment for the items on it).', max_length=255)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(blank=True, help_text='The quotation this additional scope was automatically turned into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_quotation_draft', to='so.quotation')),
                ('tracked_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_quotation_drafts', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
