# Generated by Django 5.2.3 on 2026-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0014_enquiryitem_source_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Classification'), ('rfq', 'RFQ / Enquiry'), ('submittal', 'Submittal Request'), ('not_relevant', 'Not Relevant'), ('needs_review', 'Needs Manual Review')], db_index=True, default='pending', max_length=20),
        ),
    ]
