# Generated by Django 5.2.3 on 2026-08-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0015_alter_trackedemail_status'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSubmittalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submittal', models.OneToOneField(blank=True, help_text='The submittal this additional brand/category combination was automatically turned into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_submittal_draft', to='submittal.submittal')),
                ('tracked_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_submittal_drafts', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
