# Generated by Django 5.2.3 on 2026-08-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0016_additionalsubmittaldraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittalRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tracked_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittal_request_items', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
