# Generated by Django 5.2.3 on 2026-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0017_submittalrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittaldraft',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Product category this submittal package covers, if the email's requested items carried one (see classifier.py's submittal_items and AdditionalSubmittalDraft.category, which this mirrors for the PRIMARY group).", max_length=255),
        ),
    ]
