# Generated by Django 5.2.3 on 2026-08-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0018_submittaldraft_category'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittalrequestitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text='Set once a human has selected this item and a submittal was drafted for it (see submittal_agent.draft_submittals_for_selected_items) -- excludes it from being offered for selection again on the email page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_client',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_consultant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_main_contractor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_mep_contractor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='submittal_project',
            field=models.TextField(blank=True, default=''),
        ),
    ]
