# Generated by Django 5.2.3 on 2026-08-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0019_submittalrequestitem_submittal_and_more'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text="Set once a human has selected this requirement item (checkboxes on the email page's Requirement Items table) and a submittal was drafted for it -- see submittal_agent.draft_submittal_from_enquiry_items -- excludes it from being offered for selection again. Independent of the quotation(s) this item may also be quoted on: the same item requested across multiple attachments/scopes still gets ONE submittal even though each scope keeps its own separate quotation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
    ]
