# Generated by Django 5.2.3 on 2026-08-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0020_enquiryitem_submittal'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text="No longer set by any current code path -- submittal drafting only happens from the quotation page now (see submittal_agent.draft_submittal_from_quotation), which doesn't touch this field. Kept for any historical tagging from when the (now removed) email-page 'Generate Submittal' flow set it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
        migrations.AlterField(
            model_name='submittalrequestitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text="No longer set by any current code path -- submittal drafting only happens from the quotation page now (see submittal_agent.draft_submittal_from_quotation), which doesn't touch this field. Kept for any historical tagging from when the (now removed) email-page 'Generate Submittal' flow set it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
    ]
