# Generated by Django 5.2.3 on 2026-08-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0021_alter_enquiryitem_submittal_and_more'),
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text="No longer set by any current code path -- submittal drafting from a Requirement Item only happened via the (now removed) 'Generate Submittal' action on this table; for a pure submittal-request email, use the Requested Submittal Items table instead (see SubmittalRequestItem.submittal / submittal_agent.draft_submittals_for_selected_items). Kept for any historical tagging from when that flow existed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
        migrations.AlterField(
            model_name='submittalrequestitem',
            name='submittal',
            field=models.ForeignKey(blank=True, help_text="Set once a human has selected this item (checkboxes on the email page's Requested Submittal Items table) and a submittal was drafted for it -- see submittal_agent.draft_submittals_for_selected_items -- excludes it from being offered for selection again.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submittal.submittal'),
        ),
    ]
