# Generated by Django 5.2.3 on 2026-08-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0022_alter_enquiryitem_submittal_and_more'),
        ('so', '0114_quotation_emailed_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='so.salesorder'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_name',
            field=models.CharField(choices=[('classify_email', 'Email Classification'), ('draft_quotation', 'Quotation Drafting'), ('rematch_unmatched_items', 'Unmatched Item Rematch'), ('recheck_item_brand_matches', 'Brand Match Recheck'), ('send_quotation_email', 'Quotation Sent to Client'), ('draft_submittal', 'Submittal Drafting'), ('send_submittal_email', 'Submittal Sent to Client'), ('process_lpo', 'LPO Processing')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Classification'), ('rfq', 'RFQ / Enquiry'), ('submittal', 'Submittal Request'), ('lpo', 'Purchase Order (LPO)'), ('not_relevant', 'Not Relevant'), ('needs_review', 'Needs Manual Review')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LPORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpo_number', models.CharField(blank=True, default='', max_length=100)),
                ('lpo_date', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name_stated', models.CharField(blank=True, default='', max_length=255)),
                ('referenced_quotation_number', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_terms', models.TextField(blank=True, default='')),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('total_amount', models.FloatField(blank=True, help_text="Parsed from the classifier's lpo_total_amount text (currency symbols/commas stripped) -- null if it couldn't be parsed as a number.", null=True)),
                ('status', models.CharField(choices=[('pending', 'Processing'), ('needs_review', 'Needs Review'), ('confirmed', 'Sales Order Created'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('match_method', models.CharField(choices=[('none', 'No match found'), ('exact_number', 'Exact quotation number match'), ('fuzzy_number', 'Fuzzy quotation number match'), ('customer_item_overlap', 'Customer + item overlap match')], default='none', max_length=25)),
                ('match_score', models.FloatField(blank=True, help_text="Informational only -- see lpo_agent.find_matching_quotation's confidence policy. Never gates auto-creation by itself; only an exact, unique quotation-number match does.", null=True)),
                ('match_reasoning', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_reason', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_quotations', models.ManyToManyField(blank=True, help_text='Every plausible quotation surfaced for a human to pick from on the review page when match_method is fuzzy_number/customer_item_overlap -- never populated for exact_number, since that path is unambiguous by construction.', related_name='+', to='so.quotation')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_quotation', models.ForeignKey(blank=True, help_text="The quotation this LPO was matched to, if any -- set for every match_method except 'none'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lpo_requests', to='so.quotation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.OneToOneField(blank=True, help_text='Set when lpo_agent (or a human via lpo_request_convert) successfully created a Sales Order from the matched quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lpo_request', to='so.salesorder')),
                ('source_attachment', models.ForeignKey(blank=True, help_text="The attachment the classifier tagged source='lpo_document' -- the actual PO PDF, re-served via the existing emailagent:attachment_download view rather than duplicated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emailagent.emailattachment')),
                ('tracked_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lpo_request', to='emailagent.trackedemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LPORequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lpo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emailagent.lporequest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
