# Generated by Django 5.2.3 on 2026-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0023_agentrun_sales_order_alter_agentrun_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lporequestitem',
            name='amount',
            field=models.FloatField(blank=True, help_text='Line total/extended amount.', null=True),
        ),
        migrations.AddField(
            model_name='lporequestitem',
            name='discount_percent',
            field=models.CharField(blank=True, default='', help_text='Line discount %, kept as free text (like quantity/unit) since LLM-extracted formatting is unreliable to force into a stricter field.', max_length=20),
        ),
        migrations.AddField(
            model_name='lporequestitem',
            name='extra_description',
            field=models.TextField(blank=True, default='', help_text='Secondary description text in its own column/line on the LPO (e.g. \'WITH RUBBER\' under a \'GI HANGING CLAMP 6"\' item), distinct from the main `description`. Blank if the LPO doesn\'t break these out separately.'),
        ),
        migrations.AddField(
            model_name='lporequestitem',
            name='vat_amount',
            field=models.FloatField(blank=True, help_text='Line VAT amount, if broken out per line.', null=True),
        ),
        migrations.AlterField(
            model_name='lporequestitem',
            name='price',
            field=models.FloatField(blank=True, help_text='Unit price, excl. VAT.', null=True),
        ),
    ]
