# Generated by Django 5.2.3 on 2026-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0024_lporequestitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lporequest',
            name='amount_in_words',
            field=models.CharField(blank=True, default='', help_text="The grand total spelled out in words, exactly as stated on the LPO (e.g. 'Seven thousand five hundred six and 35/100 AED ONLY'). '' if not stated.", max_length=255),
        ),
        migrations.AddField(
            model_name='lporequest',
            name='total_discount',
            field=models.FloatField(blank=True, help_text='Total discount amount stated on the LPO, if broken out as its own totals-block line.', null=True),
        ),
        migrations.AddField(
            model_name='lporequest',
            name='total_excl_vat',
            field=models.FloatField(blank=True, help_text='Total amount excl. VAT stated on the LPO, if broken out as its own totals-block line.', null=True),
        ),
        migrations.AddField(
            model_name='lporequest',
            name='total_vat',
            field=models.FloatField(blank=True, help_text='Total VAT amount stated on the LPO, if broken out as its own totals-block line.', null=True),
        ),
        migrations.AlterField(
            model_name='lporequest',
            name='total_amount',
            field=models.FloatField(blank=True, help_text="Grand total / total incl. VAT, parsed from the classifier's lpo_total_amount text (currency symbols/commas stripped) -- null if it couldn't be parsed as a number.", null=True),
        ),
    ]
