# Generated by Django 5.2.3 on 2026-08-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0025_lporequest_amount_in_words_lporequest_total_discount_and_more'),
        ('so', '0115_salesorder_created_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockShortageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lines', models.JSONField(default=list, help_text='One entry per short item, most-short first: item_code, brand, description, total_required_qty (summed across every pending LPO-sourced order needing it), available_qty (from the live stock API, null if the API call failed), final_qty (the shortfall to procure = required - available, null if available is unknown), and lpo_breakdown -- a list of {lpo_id, lpo_number, sales_order_number, quantity, payment_terms} showing exactly which LPO(s) need how much of this item.')),
                ('stock_api_error', models.TextField(blank=True, default='', help_text='Set when the live stock API call failed -- lines still list every required item with available_qty/final_qty left null (unknown) rather than being silently dropped, so procurement still sees total demand even without live stock figures.')),
                ('triggering_sales_order', models.ForeignKey(help_text='The Sales Order whose creation triggered this check -- NOT necessarily the only (or even a) contributor to every line below, since this aggregates across every pending LPO-sourced sales order at check time.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_shortage_reports', to='so.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
