# Generated by Django 5.2.3 on 2026-08-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0026_stockshortagereport'),
        ('so', '0115_salesorder_created_via'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockshortagereport',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockshortagereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockshortagereport',
            name='triggering_sales_order',
        ),
        migrations.AddField(
            model_name='stockshortagereport',
            name='last_triggered_by',
            field=models.ForeignKey(blank=True, help_text="The Sales Order whose creation (or a manual refresh, in which case this is whatever last triggered it) most recently caused a recompute -- purely informational, NOT part of this report's identity (there is only ever one row).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.salesorder'),
        ),
        migrations.AddField(
            model_name='stockshortagereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockshortagereport',
            name='lines',
            field=models.JSONField(default=list, help_text="One entry per short item, most-short first: item_code, brand, description, total_required_qty (summed across every pending LPO-sourced order needing it), available_qty (so.models.Items.total_available_stock, null if that item's stock has never been synced), final_qty (the shortfall to procure = required - available, null if available is unknown), and lpo_breakdown -- a list of {lpo_id, lpo_number, sales_order_number, customer_name, quantity, payment_terms} showing exactly which LPO(s)/customer(s) need how much of this item."),
        ),
        migrations.AlterField(
            model_name='stockshortagereport',
            name='stock_api_error',
            field=models.TextField(blank=True, default='', help_text='Set when one or more items have never had stock synced -- lines still list every required item, with available_qty/final_qty left null (unknown) rather than being silently dropped, so procurement still sees total demand even without a known stock figure for that item.'),
        ),
    ]
