# Generated by Django 5.2.3 on 2026-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0027_alter_stockshortagereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_outlook_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_outlook_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], db_index=True, default='gmail', max_length=10),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='gmail_message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
