# Generated by Django 5.2.3 on 2026-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0028_emailagentsyncstate_last_outlook_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_project_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_project_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockshortagereport',
            name='lines',
            field=models.JSONField(default=list, help_text="One entry per short item, most-short first: item_code, brand, description, total_required_qty (summed across every pending LPO-sourced order needing it), available_qty (so.models.Items.total_available_stock, null if that item's stock has never been synced), final_qty (the shortfall to procure = required - available, null if available is unknown), already_ordered_qty (quantity still outstanding on OPEN purchase orders WE placed with our own suppliers -- so.models.SAPPurchaseOrderItem, opposite direction from a customer's LPO to us), final_purchase_qty (what still needs a NEW supplier order = final_qty - already_ordered_qty, floored at 0; null if final_qty is unknown), and lpo_breakdown -- a list of {lpo_id, lpo_number, sales_order_number, customer_name, quantity, payment_terms} showing exactly which LPO(s)/customer(s) need how much of this item."),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('project', 'Project Mailbox')], db_index=True, default='gmail', max_length=10),
        ),
    ]
