# Generated by Django 5.2.3 on 2026-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0029_emailagentsyncstate_last_project_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_submittal_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailagentsyncstate',
            name='last_submittal_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('project', 'Project Mailbox'), ('submittal', 'Submittal Mailbox')], db_index=True, default='gmail', max_length=10),
        ),
    ]
