# Generated by Django 5.2.3 on 2026-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0030_emailagentsyncstate_last_submittal_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedemail',
            name='imap_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
