# Generated by Django 5.2.3 on 2026-09-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0031_trackedemail_imap_uid'),
        ('so', '0116_alter_salesorder_created_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryitem',
            name='suggested_item',
            field=models.ForeignKey(blank=True, help_text='A near-miss catalog item for an otherwise-unmatched requirement line, offered to the reviewer as a substitute to accept or ignore. Never quoted automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.items'),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='suggested_reason',
            field=models.CharField(blank=True, default='', help_text="How the suggested item differs from what the customer asked for, in the agent's own words (e.g. 'grey 4m instead of red 5.8m push-fit') -- shown beside the Add button so a reviewer sees what they are accepting.", max_length=255),
        ),
    ]
