# Generated by Django 5.2.3 on 2026-09-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0032_enquiryitem_suggested_item_and_more'),
        ('so', '0116_alter_salesorder_created_via'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryitem',
            name='suggested_item',
        ),
        migrations.RemoveField(
            model_name='enquiryitem',
            name='suggested_reason',
        ),
        migrations.CreateModel(
            name='EnquiryItemSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', help_text='How THIS item differs from what the customer asked for, in the agent\'s own words (e.g. \'4" (113-118mm) -- one size under the 125mm requested\') -- shown beside its Add button so a reviewer sees what they are accepting. Each suggestion carries its own, since that is what distinguishes them.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text="The agent's own ranking, best first -- suggestions are shown in this order.")),
                ('enquiry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='emailagent.enquiryitem')),
                ('item', models.ForeignKey(help_text='The catalog item being offered as a substitute.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='so.items')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('enquiry_item', 'item'), name='unique_suggestion_per_enquiry_item')],
            },
        ),
    ]
