# Generated by Django 5.2.3 on 2026-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0033_remove_enquiryitem_suggested_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lporequest',
            name='customer_name_source',
            field=models.CharField(blank=True, default='', help_text="Where customer_name_stated was read from, e.g. 'letterhead logo' -- 'email classifier' when the dedicated LPO customer extraction found nothing and the classifier's value was kept.", max_length=100),
        ),
        migrations.AddField(
            model_name='lporequest',
            name='customer_trn_stated',
            field=models.CharField(blank=True, default='', help_text="Buyer's TRN as printed on the LPO (lpo_agent.refine_lpo_customer) -- matched against so.Customer.vat_number before the name.", max_length=50),
        ),
    ]
