# Generated by Django 5.2.3 on 2026-10-02 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0034_lpo_request_customer_trn_and_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='upload_customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='upload_salesman_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailagent_uploaded_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackedemail',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('project', 'Project Mailbox'), ('submittal', 'Submittal Mailbox'), ('upload', 'Manual Upload')], db_index=True, default='gmail', max_length=10),
        ),
    ]
