# Generated by Django 5.2.3 on 2026-10-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailagent', '0035_manual_upload_enquiry'),
        ('so', '0116_alter_salesorder_created_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedemail',
            name='upload_customer',
            field=models.ForeignKey(blank=True, help_text='Customer picked on the upload form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.customer'),
        ),
        migrations.AddField(
            model_name='trackedemail',
            name='upload_salesman',
            field=models.ForeignKey(blank=True, help_text='Salesman picked on the upload form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='so.salesman'),
        ),
    ]
