# Generated by Django 5.2.3 on 2025-06-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0002_salesman_customer_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_custom_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='so.salesman'),
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.items')),
            ],
            options={
                'unique_together': {('customer', 'item')},
            },
        ),
    ]
