# Generated by Django 5.2.3 on 2025-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0003_orderitem_is_custom_price_salesorder_salesman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='order_number',
        ),
    ]
