# Generated by Django 5.2.3 on 2025-06-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0004_remove_salesorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_taken',
            field=models.BooleanField(default=False),
        ),
    ]
