# Generated by Django 5.2.3 on 2025-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0005_salesorder_order_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
