# Generated by Django 5.2.3 on 2025-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='lpo_image',
            field=models.ImageField(blank=True, null=True, upload_to='lpo_uploads/'),
        ),
    ]
