# Generated by Django 5.2.3 on 2025-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0008_salesorder_lpo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
