# Generated by Django 5.2.3 on 2025-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0009_salesorder_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprice',
            name='custom_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
