# Generated by Django 5.2.3 on 2025-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0010_alter_customerprice_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
