# Generated by Django 5.2.3 on 2025-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0011_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_upvc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
