# Generated by Django 5.2.3 on 2025-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0012_items_item_cost_items_item_upvc'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['item_firm'], name='so_items_item_fi_f7bdf2_idx'),
        ),
    ]
