# Generated by Django 5.2.3 on 2025-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0013_items_so_items_item_fi_f7bdf2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='month_pending_6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='old_months_pending',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='pdc_received',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_outstanding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_outstanding_with_pdc',
            field=models.FloatField(default=0.0),
        ),
    ]
