# Generated by Django 5.2.3 on 2025-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0014_customer_credit_days_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_days',
            field=models.CharField(default='0'),
        ),
    ]
