# Generated by Django 5.2.3 on 2025-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0015_alter_customer_credit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hold by A/c', 'Hold by A/c'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_days',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax',
            field=models.FloatField(default=5.0),
        ),
    ]
