# Generated by Django 5.2.3 on 2025-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0016_salesorder_order_status_alter_customer_credit_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
