# Generated by Django 5.2.3 on 2025-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0017_salesorder_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
