# Generated by Django 5.2.3 on 2025-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0019_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
