# Generated by Django 5.2.3 on 2025-09-22 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0020_remove_customer_location_salesorder_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hold by A/c', 'Hold by A/c'), ('Approved', 'Approved'), ('SO Created', 'SO Created')], default='Pending', max_length=20),
        ),
    ]
