# Generated by Django 5.2.3 on 2025-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0021_salesorder_approved_by_alter_salesorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
