# Generated by Django 5.2.3 on 2025-09-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0023_quotation_quotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='so.items'),
        ),
    ]
