# Generated by Django 5.2.3 on 2025-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0025_quotation_status_alter_quotation_quotation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
