# Generated by Django 5.2.3 on 2025-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0026_quotationitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
