# Generated by Django 5.2.3 on 2025-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0027_salesorder_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
