# Generated by Django 5.2.3 on 2025-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0028_quotationitem_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='remarks',
        ),
        migrations.AddField(
            model_name='quotation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
