# Generated by Django 5.2.3 on 2025-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0029_remove_quotationitem_remarks_quotation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_days',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
