# Generated by Django 5.2.3 on 2025-10-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0030_alter_customer_credit_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.CharField(max_length=100, unique=True)),
                ('internal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('salesman_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('bp_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_sapquota_posting_125cab_idx'), models.Index(fields=['salesman_name'], name='so_sapquota_salesma_1e63fd_idx'), models.Index(fields=['customer_name'], name='so_sapquota_custome_169168_idx'), models.Index(fields=['status'], name='so_sapquota_status_e5cacc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='so.sapquotation')),
            ],
        ),
    ]
