# Generated by Django 5.2.3 on 2025-10-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0031_sapquotation_sapquotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapquotation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
