# Generated by Django 5.2.3 on 2025-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0032_sapquotation_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapquotation',
            name='bill_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
