# Generated by Django 5.2.3 on 2025-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0033_sapquotation_bill_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_description',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_upvc',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
