# Generated by Django 5.2.3 on 2025-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0035_quotationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlog',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotationlog',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotationlog',
            name='network_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
