# Generated by Django 5.2.3 on 2025-11-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0037_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_logs', to='so.device'),
        ),
    ]
