# Generated by Django 5.2.3 on 2025-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0038_quotationlog_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlog',
            name='device_browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationlog',
            name='device_os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
