# Generated by Django 5.2.3 on 2025-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0039_quotationlog_device_browser_quotationlog_device_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
