# Generated by Django 5.2.3 on 2025-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0040_device_last_lat_device_last_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=50)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('bp_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('item_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('row_total', models.FloatField(default=0.0)),
                ('open_qty', models.FloatField(default=0.0)),
                ('total_available', models.FloatField(default=0.0)),
                ('salesman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_opensale_posting_7f6863_idx'), models.Index(fields=['salesman_name'], name='so_opensale_salesma_07cf2f_idx'), models.Index(fields=['manufacturer'], name='so_opensale_manufac_3846be_idx')],
            },
        ),
    ]
