# Generated by Django 5.2.3 on 2025-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0043_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='salesman_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
