# Generated by Django 5.2.3 on 2026-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0044_salesorder_salesman_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='division',
            field=models.CharField(choices=[('JUNAID', 'Junaid'), ('ALABAMA', 'Alabama')], default='JUNAID', max_length=20),
        ),
    ]
