# Generated by Django 5.2.3 on 2026-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0045_salesorder_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='division',
            field=models.CharField(choices=[('JUNAID', 'Junaid World'), ('ALABAMA', 'Alabama')], default='JUNAID', max_length=20),
        ),
    ]
