# Generated by Django 5.2.3 on 2026-01-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0046_quotation_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPSalesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=100, unique=True)),
                ('internal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('salesman_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('bp_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bill_to', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_sapsales_posting_b1a2ac_idx'), models.Index(fields=['salesman_name'], name='so_sapsales_salesma_e0f1f1_idx'), models.Index(fields=['customer_name'], name='so_sapsales_custome_0b402f_idx'), models.Index(fields=['status'], name='so_sapsales_status_e04111_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPSalesorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='so.sapsalesorder')),
            ],
        ),
    ]
