# Generated by Django 5.2.3 on 2026-01-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0047_sapsalesorder_sapsalesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='row_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='dip_warehouse_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='manufacture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='remaining_open_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='row_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='total_available_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
