# Generated by Django 5.2.3 on 2026-01-16 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0048_sapsalesorder_row_total_sum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_number', models.CharField(help_text='Format: <SO_NUMBER>-P<N>', max_length=100, unique=True)),
                ('sequence', models.IntegerField(help_text='Sequence number (1, 2, 3...) within the SO')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['salesorder', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='SAPProformaInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(help_text='SO number for re-upload safety', max_length=100)),
                ('line_no', models.IntegerField(help_text='Line number from SO item')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='line_no',
            field=models.IntegerField(default=1, help_text='Line number within the sales order (1-based)'),
        ),
        migrations.AddIndex(
            model_name='sapsalesorderitem',
            index=models.Index(fields=['salesorder', 'line_no'], name='so_sapsales_salesor_2556c6_idx'),
        ),
        migrations.AddField(
            model_name='sapproformainvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sapproformainvoice',
            name='salesorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='so.sapsalesorder'),
        ),
        migrations.AddField(
            model_name='sapproformainvoiceline',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='so.sapproformainvoice'),
        ),
        migrations.AddIndex(
            model_name='sapproformainvoice',
            index=models.Index(fields=['salesorder', 'sequence'], name='so_sapprofo_salesor_d47a57_idx'),
        ),
        migrations.AddIndex(
            model_name='sapproformainvoice',
            index=models.Index(fields=['status'], name='so_sapprofo_status_f4b035_idx'),
        ),
        migrations.AddIndex(
            model_name='sapproformainvoiceline',
            index=models.Index(fields=['pi'], name='so_sapprofo_pi_id_af3aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='sapproformainvoiceline',
            index=models.Index(fields=['so_number', 'line_no'], name='so_sapprofo_so_numb_9a3366_idx'),
        ),
    ]
