# Generated by Django 5.2.3 on 2026-01-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0049_add_pi_models_and_line_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoiceline',
            name='so_item',
            field=models.ForeignKey(blank=True, help_text='Direct reference to SO item (for accurate allocation)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='so.sapsalesorderitem'),
        ),
        migrations.AddIndex(
            model_name='sapproformainvoiceline',
            index=models.Index(fields=['so_item'], name='so_sapprofo_so_item_ed936e_idx'),
        ),
    ]
