# Generated by Django 5.2.3 on 2026-01-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0050_add_item_id_to_pi_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoice',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks/notes for the Proforma Invoice', null=True),
        ),
        migrations.AddField(
            model_name='sapproformainvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pis', to=settings.AUTH_USER_MODEL),
        ),
    ]
