# Generated by Django 5.2.3 on 2026-01-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0052_proformainvoicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Number - Business Partner', max_length=100, null=True),
        ),
    ]
