# Generated by Django 5.2.3 on 2026-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0053_add_vat_number_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for the entire sales order', max_digits=5),
        ),
    ]
