# Generated by Django 5.2.3 on 2026-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0054_add_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Number - Business Partner (from Excel upload)', max_length=100, null=True),
        ),
    ]
