# Generated by Django 5.2.3 on 2026-01-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0055_add_vat_number_to_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoice',
            name='lpo_date',
            field=models.DateField(blank=True, help_text='LPO date for this Proforma Invoice', null=True),
        ),
    ]
