# Generated by Django 5.2.3 on 2026-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0056_add_pi_lpo_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sapsalesorderitem',
            index=models.Index(fields=['item_no'], name='so_sapsales_item_no_a16516_idx'),
        ),
        migrations.AddIndex(
            model_name='sapsalesorderitem',
            index=models.Index(fields=['pending_amount'], name='so_sapsales_pending_494d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='sapsalesorderitem',
            index=models.Index(fields=['row_status'], name='so_sapsales_row_sta_081a31_idx'),
        ),
    ]
