# Generated by Django 5.2.3 on 2026-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0057_sapsalesorderitem_so_sapsales_item_no_a16516_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoice',
            name='is_sap_pi',
            field=models.BooleanField(default=False, help_text='True if this PI was created in SAP (U_PROFORMAINVOICE=Y)'),
        ),
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='pi_number',
            field=models.CharField(help_text='Format: <SO_NUMBER>-P<N> for app PIs, <SO_NUMBER>-SAP for SAP PIs', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='sequence',
            field=models.IntegerField(help_text='Sequence number (1, 2, 3...) within the SO. For SAP PIs, use 0.'),
        ),
    ]
