# Generated by Django 5.2.3 on 2026-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0058_sapproformainvoice_is_sap_pi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='is_sap_pi',
            field=models.BooleanField(default=False, help_text='True if this SO has a Proforma Invoice created in SAP (U_PROFORMAINVOICE=Y)'),
        ),
    ]
