# Generated by Django 5.2.3 on 2026-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0059_sapsalesorder_is_sap_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Customer address from SAP API', null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorder',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Customer address from SAP API (Address field)', null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorder',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone from SAP API (BusinessPartner.Phone1)', max_length=50, null=True),
        ),
    ]
