# Generated by Django 5.2.3 on 2026-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0060_customer_address_sapsalesorder_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
