# Generated by Django 5.2.3 on 2026-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0061_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='pi_number',
            field=models.CharField(help_text='Format: <SO_NUMBER>-P<N> for app PIs, <SO_NUMBER> for SAP PIs', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sapproformainvoice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
