# Generated by Django 5.2.3 on 2026-01-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0062_alter_sapproformainvoice_pi_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoice',
            name='pi_date',
            field=models.DateField(blank=True, help_text='PI date - SO date for SAP PIs, creation date for app PIs', null=True),
        ),
    ]
