# Generated by Django 5.2.3 on 2026-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0063_sapproformainvoice_pi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dip_warehouse_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DIP warehouse stock from API (dip_stock)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='total_available_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total stock from API (total_stock)', max_digits=12, null=True),
        ),
    ]
