# Generated by Django 5.2.3 on 2026-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0064_items_dip_warehouse_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='closing_remarks',
            field=models.TextField(blank=True, help_text='Closing remarks from SAP API (ClosingRemarks field) - used as default remarks for SAP PIs', null=True),
        ),
    ]
