# Generated by Django 5.2.3 on 2026-01-27 08:10

import so.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0065_add_closing_remarks_to_sapsalesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapproformainvoice',
            name='cheque_attachment',
            field=models.FileField(blank=True, help_text='Cheque copy (PDF/Image)', null=True, upload_to=so.models.cheque_upload_path),
        ),
        migrations.AddField(
            model_name='sapproformainvoice',
            name='cheque_received',
            field=models.BooleanField(default=False, help_text='Auto-set to Yes when cheque attachment is uploaded'),
        ),
    ]
