# Generated by Django 5.2.3 on 2026-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0066_add_cheque_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_display_name',
            field=models.CharField(blank=True, help_text='Optional display name for walk-in/CASH customers', max_length=255, null=True),
        ),
    ]
