# Generated by Django 5.2.3 on 2026-02-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0067_add_customer_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPARCreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_memo_number', models.CharField(help_text='DocNum from API', max_length=100, unique=True)),
                ('internal_number', models.CharField(blank=True, help_text='DocEntry from API', max_length=100, null=True)),
                ('posting_date', models.DateField(blank=True, help_text='DocDate from API', null=True)),
                ('doc_due_date', models.DateField(blank=True, help_text='DocDueDate from API', null=True)),
                ('customer_code', models.CharField(blank=True, help_text='CardCode from API', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='CardName from API', max_length=255)),
                ('customer_address', models.TextField(blank=True, help_text='Address from API', null=True)),
                ('salesman_name', models.CharField(blank=True, help_text='SalesPerson.SalesEmployeeName from API', max_length=255, null=True)),
                ('salesman_code', models.IntegerField(blank=True, help_text='SalesPerson.SalesEmployeeCode from API', null=True)),
                ('bp_reference_no', models.CharField(blank=True, help_text='NumAtCard from API', max_length=255, null=True)),
                ('doc_total', models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal from API (with VAT)', max_digits=12, null=True)),
                ('doc_total_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal - VatSum (calculated)', max_digits=12, null=True)),
                ('vat_sum', models.DecimalField(blank=True, decimal_places=2, help_text='VatSum from API', max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='DiscountPercent from API', max_digits=5)),
                ('cancel_status', models.CharField(blank=True, help_text='CancelStatus: csNo, csYes, csCancellation', max_length=50, null=True)),
                ('document_status', models.CharField(blank=True, help_text='DocumentStatus from API', max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='FederalTaxID from API (VAT number)', max_length=100, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_saparcre_posting_ebfc4b_idx'), models.Index(fields=['customer_code'], name='so_saparcre_custome_900644_idx'), models.Index(fields=['cancel_status'], name='so_saparcre_cancel__7249b1_idx'), models.Index(fields=['customer_name'], name='so_saparcre_custome_bb3d4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='DocNum from API', max_length=100, unique=True)),
                ('internal_number', models.CharField(blank=True, help_text='DocEntry from API', max_length=100, null=True)),
                ('posting_date', models.DateField(blank=True, help_text='DocDate from API', null=True)),
                ('doc_due_date', models.DateField(blank=True, help_text='DocDueDate from API', null=True)),
                ('customer_code', models.CharField(blank=True, help_text='CardCode from API', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='CardName from API', max_length=255)),
                ('customer_address', models.TextField(blank=True, help_text='Address from API', null=True)),
                ('salesman_name', models.CharField(blank=True, help_text='SalesPerson.SalesEmployeeName from API', max_length=255, null=True)),
                ('salesman_code', models.IntegerField(blank=True, help_text='SalesPerson.SalesEmployeeCode from API', null=True)),
                ('bp_reference_no', models.CharField(blank=True, help_text='NumAtCard from API', max_length=255, null=True)),
                ('doc_total', models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal from API (with VAT)', max_digits=12, null=True)),
                ('doc_total_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal - VatSum (calculated)', max_digits=12, null=True)),
                ('vat_sum', models.DecimalField(blank=True, decimal_places=2, help_text='VatSum from API', max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='DiscountPercent from API', max_digits=5)),
                ('cancel_status', models.CharField(blank=True, help_text='CancelStatus: csNo, csYes, csCancellation', max_length=50, null=True)),
                ('document_status', models.CharField(blank=True, help_text='DocumentStatus from API', max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='FederalTaxID from API (VAT number)', max_length=100, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_saparinv_posting_8b6f14_idx'), models.Index(fields=['customer_code'], name='so_saparinv_custome_18e995_idx'), models.Index(fields=['cancel_status'], name='so_saparinv_cancel__32a0f9_idx'), models.Index(fields=['customer_name'], name='so_saparinv_custome_b519e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPARCreditMemoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1, help_text='LineNum from API (0-based, converted to 1-based)')),
                ('item_code', models.CharField(blank=True, help_text='ItemCode from API', max_length=100, null=True)),
                ('item_description', models.CharField(help_text='ItemDescription from API', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity from API', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price from API', max_digits=12)),
                ('price_after_vat', models.DecimalField(blank=True, decimal_places=2, help_text='PriceAfterVAT from API', max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='DiscountPercent from API', max_digits=5)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='LineTotal from API', max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='TaxPercentagePerRow from API', max_digits=5, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, help_text='TaxTotal from API', max_digits=12, null=True)),
                ('upc_code', models.CharField(blank=True, help_text='U_UPCCODE from API', max_length=100, null=True)),
                ('credit_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='so.saparcreditmemo')),
                ('item', models.ForeignKey(blank=True, help_text='Link to Items table for analytics', null=True, on_delete=django.db.models.deletion.SET_NULL, to='so.items')),
            ],
            options={
                'indexes': [models.Index(fields=['credit_memo', 'line_no'], name='so_saparcre_credit__57e3d6_idx'), models.Index(fields=['item_code'], name='so_saparcre_item_co_0e952e_idx'), models.Index(fields=['item'], name='so_saparcre_item_id_a41d01_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPARInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1, help_text='LineNum from API (0-based, converted to 1-based)')),
                ('item_code', models.CharField(blank=True, help_text='ItemCode from API', max_length=100, null=True)),
                ('item_description', models.CharField(help_text='ItemDescription from API', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity from API', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price from API', max_digits=12)),
                ('price_after_vat', models.DecimalField(blank=True, decimal_places=2, help_text='PriceAfterVAT from API', max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='DiscountPercent from API', max_digits=5)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='LineTotal from API', max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='TaxPercentagePerRow from API', max_digits=5, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, help_text='TaxTotal from API', max_digits=12, null=True)),
                ('upc_code', models.CharField(blank=True, help_text='U_UPCCODE from API', max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='so.saparinvoice')),
                ('item', models.ForeignKey(blank=True, help_text='Link to Items table for analytics', null=True, on_delete=django.db.models.deletion.SET_NULL, to='so.items')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice', 'line_no'], name='so_saparinv_invoice_c56c99_idx'), models.Index(fields=['item_code'], name='so_saparinv_item_co_1450f1_idx'), models.Index(fields=['item'], name='so_saparinv_item_id_dac35a_idx')],
            },
        ),
    ]
