# Generated by Django 5.2.3 on 2026-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0068_saparcreditmemo_saparinvoice_saparcreditmemoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparinvoice',
            name='rounding_diff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RoundingDiffAmount from API (added to doc_total_without_vat, not to doc_total)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saparinvoice',
            name='doc_total_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal - VatSum (calculated) + RoundingDiffAmount if present', max_digits=12, null=True),
        ),
    ]
