# Generated by Django 5.2.3 on 2026-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0069_add_rounding_diff_amount_to_arinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemo',
            name='rounding_diff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RoundingDiffAmount from API (subtracted from doc_total_without_vat, not from doc_total)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saparcreditmemo',
            name='doc_total_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal - VatSum - RoundingDiffAmount (if negative like -10.4, subtracting it gives actual subtotal)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saparinvoice',
            name='doc_total_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DocTotal - VatSum - RoundingDiffAmount (if negative like -10.4, subtracting it gives actual subtotal)', max_digits=12, null=True),
        ),
    ]
