# Generated by Django 5.2.3 on 2026-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0070_add_rounding_diff_amount_to_arcreditmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemo',
            name='store',
            field=models.CharField(blank=True, help_text="Store: 'HO' or 'Others' (based on salesman_name: 'R.' or 'E.' prefix = 'Others', else 'HO')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoice',
            name='store',
            field=models.CharField(blank=True, help_text="Store: 'HO' or 'Others' (based on salesman_name: 'R.' or 'E.' prefix = 'Others', else 'HO')", max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='saparcreditmemo',
            index=models.Index(fields=['store'], name='so_saparcre_store_3bf7d0_idx'),
        ),
    ]
