# Generated by Django 5.2.3 on 2026-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0071_add_store_field_to_ar_invoice_creditmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemoitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GrossProfitTotalBasePrice from API (total cost price for this line)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparcreditmemoitem',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Profit = LineTotal - cost_price (calculated)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoice',
            name='total_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Gross Profit = sum of all item gross_profit (calculated)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoiceitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GrossProfitTotalBasePrice from API (total cost price for this line)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoiceitem',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Profit = LineTotal - cost_price (calculated)', max_digits=12, null=True),
        ),
    ]
