# Generated by Django 5.2.3 on 2026-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0072_add_gross_profit_fields_to_ar_invoice_creditmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemo',
            name='total_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Gross Profit = sum of all item gross_profit (calculated)', max_digits=12, null=True),
        ),
    ]
