# Generated by Django 5.2.3 on 2026-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0073_add_total_gross_profit_to_credit_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemo',
            name='subtotal_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal after applying header discount (sum of all line_total_after_discount)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparcreditmemoitem',
            name='line_total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LineTotal after applying header discount (for display)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoice',
            name='subtotal_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal after applying header discount (sum of all line_total_after_discount)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoiceitem',
            name='line_total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LineTotal after applying header discount (for display)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saparcreditmemoitem',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Profit = LineTotal after discount - cost_price (calculated)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saparinvoiceitem',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Profit = LineTotal after discount - cost_price (calculated)', max_digits=12, null=True),
        ),
    ]
