# Generated by Django 5.2.3 on 2026-02-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0074_saparcreditmemo_subtotal_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saparcreditmemo',
            name='subtotal_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal before discount = doc_total_without_vat + TotalDiscount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saparinvoice',
            name='subtotal_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal before discount = doc_total_without_vat + TotalDiscount', max_digits=12, null=True),
        ),
    ]
