# Generated by Django 5.2.3 on 2026-02-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0075_saparcreditmemo_subtotal_before_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saparcreditmemo',
            name='subtotal_after_discount',
        ),
        migrations.RemoveField(
            model_name='saparinvoice',
            name='subtotal_after_discount',
        ),
    ]
