# Generated by Django 5.2.3 on 2026-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0076_remove_subtotal_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='very_old_months_pending',
            field=models.FloatField(default=0.0, help_text='360+ days pending (6++ months)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='old_months_pending',
            field=models.FloatField(default=0.0, help_text='180+ days pending (6+ months)'),
        ),
    ]
