# Generated by Django 5.2.3 on 2026-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0077_add_very_old_months_pending'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saparcreditmemoitem',
            index=models.Index(fields=['item_code', 'credit_memo'], name='so_saparcre_item_co_aa5cfc_idx'),
        ),
    ]
