# Generated by Django 5.2.3 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0078_saparcreditmemoitem_so_saparcre_item_co_aa5cfc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapquotation',
            name='vat_sum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VatSum from API', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapquotation',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TotalDiscount from API (header level)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapquotation',
            name='rounding_diff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RoundingDiffAmount from API', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sapquotation',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='DiscountPercent from API (header level, optional)', max_digits=5, null=True),
        ),
    ]

