# Generated by Django 5.2.3 on 2026-02-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0080_normalize_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='converted_to_sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales order created from this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='so.salesorder'),
        ),
    ]
