# Generated by Django 5.2.3 on 2026-02-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0081_quotation_converted_to_sales_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCreditEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_credit_limit', models.FloatField(default=0.0)),
                ('edited_credit_days', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_credit_edits', to='so.customer')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_credit_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='so_financec_created_d441af_idx'), models.Index(fields=['customer'], name='so_financec_custome_d44a97_idx'), models.Index(fields=['edited_by'], name='so_financec_edited__93cca7_idx')],
            },
        ),
    ]
