# Generated by Django 5.2.3 on 2026-02-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0082_financecrediteditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('internal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bp_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('salesman_name', models.CharField(blank=True, help_text='Purchaser/salesman name', max_length=255, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('row_total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='so_sappurch_posting_ca1fa1_idx'), models.Index(fields=['supplier_name'], name='so_sappurch_supplie_6bb9fc_idx'), models.Index(fields=['status'], name='so_sappurch_status_abc84d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1, help_text='Line number within the purchase order (1-based)')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('row_status', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('remaining_open_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='so.sappurchaseorder')),
            ],
            options={
                'indexes': [models.Index(fields=['purchaseorder', 'line_no'], name='so_sappurch_purchas_727b96_idx'), models.Index(fields=['item_no'], name='so_sappurch_item_no_b3b96b_idx'), models.Index(fields=['row_status'], name='so_sappurch_row_sta_287492_idx')],
            },
        ),
    ]
