# Generated by Django 5.2.3 on 2026-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0083_add_sap_purchase_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='internal_remarks',
            field=models.TextField(blank=True, help_text="Manager internal remarks for salesman (optional; shown on PDF when 'include internal remarks' is on)", null=True),
        ),
    ]
