# Generated by Django 5.2.3 on 2026-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0084_add_customer_internal_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='nf_ref',
            field=models.CharField(blank=True, help_text='NFRef from TaxExtension - quotation reference', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='sapsalesorder',
            index=models.Index(fields=['nf_ref'], name='so_sapsales_nf_ref_d537ca_idx'),
        ),
    ]
