# Generated by Django 5.2.3 on 2026-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0086_add_proposed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.CharField(choices=[('Junaid', 'Junaid'), ('Alabama', 'Alabama')], default='Junaid', max_length=20),
        ),
    ]
