# Generated by Django 5.2.3 on 2026-02-28 06:12

from django.db import migrations


def set_alabama_company(apps, schema_editor):
    Role = apps.get_model('so', 'Role')
    User = apps.get_model('auth', 'User')
    alabama_usernames = ['alabamaadmin', 'alabamakadhar', 'alabamamusharaf']
    for u in User.objects.filter(username__in=alabama_usernames):
        try:
            role = Role.objects.get(user=u)
            role.company = 'Alabama'
            role.save()
        except Role.DoesNotExist:
            pass


def reverse_set_alabama_company(apps, schema_editor):
    Role = apps.get_model('so', 'Role')
    User = apps.get_model('auth', 'User')
    alabama_usernames = ['alabamaadmin', 'alabamakadhar', 'alabamamusharaf']
    for u in User.objects.filter(username__in=alabama_usernames):
        try:
            role = Role.objects.get(user=u)
            role.company = 'Junaid'
            role.save()
        except Role.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0087_add_role_company'),
    ]

    operations = [
        migrations.RunPython(set_alabama_company, reverse_set_alabama_company),
    ]
