# Generated by Django 5.2.3 on 2026-03-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0088_set_alabama_users_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status (Admin only)', max_length=20),
        ),
    ]
