# Generated by Django 5.2.3 on 2026-03-07 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0089_add_sapsalesorder_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='approval_updated_at',
            field=models.DateTimeField(blank=True, help_text='When approval status was last updated', null=True),
        ),
        migrations.AddField(
            model_name='sapsalesorder',
            name='approval_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated approval status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sapsalesorder_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
