# Generated by Django 5.2.3 on 2026-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0090_add_approval_updated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapsalesorder',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('DO Completed', 'DO Completed'), ('Partial DO', 'Partial DO'), ('Trade License Expired', 'Trade License Expired')], default='Pending', help_text='Approval status (Admin only)', max_length=30),
        ),
    ]
