# Generated by Django 5.2.3 on 2026-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0092_add_md_approval_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='sap_remarks',
            field=models.TextField(blank=True, help_text='Comments from SAP API (Comments field) - e.g. PRICE NEED TO BE CHANGED, Based On Sales Quotations', null=True),
        ),
    ]
