# Generated by Django 5.2.3 on 2026-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0093_add_sap_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorder',
            name='salesman_remarks',
            field=models.TextField(blank=True, help_text='Remarks from salesman (salesman can edit)', null=True),
        ),
        migrations.AlterField(
            model_name='sapsalesorder',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal remarks (Admin only - salesman can view)', null=True),
        ),
    ]
