# Generated by Django 5.2.3 on 2026-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0094_add_salesman_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsalesorderitem',
            name='revised_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional revised unit price (salesman can edit)', max_digits=12, null=True),
        ),
    ]
