# Generated by Django 5.2.3 on 2026-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0096_rename_do_completed_to_so_closed_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapsalesorder',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('SO Closed/Completed', 'SO Closed/Completed'), ('Partial DO', 'Partial DO'), ('Trade License Expired', 'Trade License Expired'), ('MD Approval Required', 'MD Approval Required')], default='Pending', help_text='Approval status (Admin only)', max_length=30),
        ),
    ]
