# Generated by Django 5.2.3 on 2026-03-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0097_alter_sapsalesorder_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit Memo', 'Credit Memo')], max_length=20)),
                ('document_type_code', models.CharField(blank=True, max_length=20, null=True)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('posting_date', models.DateField(db_index=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('item_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sales_lines', to='so.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sales_lines', to='so.items')),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'document_number'], name='so_historic_documen_1f7896_idx'), models.Index(fields=['posting_date'], name='so_historic_posting_3af5f9_idx'), models.Index(fields=['sales_employee'], name='so_historic_sales_e_d73525_idx')],
            },
        ),
    ]
