# Generated by Django 5.2.3 on 2026-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0099_add_scheduled_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsRecordingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('invoice', 'Invoice'), ('credit_memo', 'Credit Memo')], max_length=20)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('ctrl_number', models.CharField(blank=True, max_length=100, null=True)),
                ('handed_to_salesman', models.CharField(blank=True, help_text='Empty = same as document salesman', max_length=255, null=True)),
                ('handed_over_date', models.DateField(blank=True, null=True)),
                ('received_back', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('with_salesman', 'With Salesman'), ('in_store', 'In Store'), ('received_by_ac', 'Received by A/c')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['document_kind', 'document_number'], name='so_accounts_documen_39b8d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_kind', 'document_number'), name='unique_accounts_recording_document')],
            },
        ),
    ]
