# Generated by Django 5.2.3 on 2026-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0100_accounts_recording_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsrecordingentry',
            name='accounts_internal_remark',
            field=models.TextField(blank=True, help_text='Accounts-only internal note; shown on Accounts Recording list and detail.', null=True),
        ),
    ]
