# Generated by Django 5.2.3 on 2026-03-27 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0101_accounts_internal_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsRecordingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document_kind', models.CharField(max_length=20)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('changes', models.JSONField(default=dict, help_text='Map of field key to {"old": "...", "new": "..."}')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_recording_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_kind', 'document_number', '-created_at'], name='so_accounts_documen_acc4a2_idx')],
            },
        ),
    ]
