# Generated by Django 5.2.3 on 2026-03-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0102_accounts_recording_change_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPendingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.BigIntegerField()),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('num_at_card', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_total', models.FloatField(default=0.0)),
                ('paid_to_date', models.FloatField(default=0.0)),
                ('balance_due', models.FloatField(default=0.0)),
                ('slp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invoices', to='so.customer')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['customer', 'doc_date'], name='so_customer_custome_e879ed_idx'),
                    models.Index(fields=['customer', 'balance_due'], name='so_customer_custome_1d9e91_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('customer', 'doc_num'), name='unique_customer_pending_invoice_docnum'),
                ],
            },
        ),
    ]
