# Generated by Django 5.2.3 on 2026-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0105_sapsalesorder_management_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapquotation',
            name='sales_director_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapquotation',
            name='salesman_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
