# Generated by Django 5.2.3 on 2026-06-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0106_sapquotation_sales_director_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='license_name',
            field=models.CharField(blank=True, choices=[('JUNAID_MAIN', 'JUNAID SANITARY & ELECTRICAL REQUISITES TRADING LLC'), ('JUNAID_SME', 'JUNAID SANITARY AND ELECTRICAL REQUISITES TRADING L.L.C - DUBAI BRANCH'), ('JUNAID_MAT', 'JUNAID SANITARY & ELECTRICAL MATERIALS TRADING (LLC.) (DUBAI BR)')], default='JUNAID_MAIN', max_length=20, null=True),
        ),
    ]
