# Generated by Django 5.2.3 on 2026-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0107_add_license_name_to_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='license_name',
            field=models.CharField(blank=True, choices=[('JUNAID_SME', 'JUNAID SANITARY AND ELECTRICAL REQUISITES TRADING L.L.C - DUBAI BRANCH'), ('JUNAID_MAT', 'JUNAID SANITARY & ELECTRICAL MATERIALS TRADING (LLC.) (DUBAI BR)')], default='JUNAID_SME', max_length=20, null=True),
        ),
    ]
