# Generated by Django 5.2.3 on 2026-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0108_update_license_name_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
