# Generated by Django 5.2.3 on 2026-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0109_add_phone_to_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmappedSalesmanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_name', models.CharField(max_length=255, unique=True)),
                ('customer_count', models.IntegerField(default=0)),
                ('sample_customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-customer_count'],
            },
        ),
    ]
