# Generated by Django 5.2.3 on 2026-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0110_unmappedsalesmanname'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.FloatField(default=0.0, help_text='Resolved currency value of the discount, computed from discount_type/discount_value against the subtotal'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Independent of `status` (which tracks undercost auto-approval). Any non-zero discount requires manager approval here.', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percentage'), ('AMOUNT', 'Fixed Amount')], help_text='Whether discount_value is a percentage or a fixed amount', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_value',
            field=models.FloatField(default=0.0, help_text='Raw value entered by the salesman (e.g. 10 for 10%, or 500 for AED 500)'),
        ),
    ]
