# Generated by Django 5.2.3 on 2026-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0111_add_quotation_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('discount_approved', 'Discount Approved'), ('discount_rejected', 'Discount Rejected')], default='created', max_length=20),
        ),
    ]
