# Generated by Django 5.2.3 on 2026-08-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0112_add_discount_actions_to_quotationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='When the quotation was last sent to the client via the Send Quotation button', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='emailed_to',
            field=models.CharField(blank=True, help_text='Comma-separated recipient address(es) the quotation PDF was last emailed to', max_length=500, null=True),
        ),
    ]
