# Generated by Django 5.2.3 on 2026-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0113_quotation_emailed_at_quotation_emailed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='emailed_message_id',
            field=models.CharField(blank=True, help_text="Message-ID header of the last 'Send Quotation' email. Lets a customer's reply be matched back to this quotation (via its In-Reply-To/References headers) even when Gmail assigns the reply a different thread_id than the original enquiry -- e.g. because this email was sent via SMTP rather than through the watched Gmail account, so Gmail has no record of it belonging to that thread.", max_length=255, null=True),
        ),
    ]
