# Generated by Django 5.2.3 on 2026-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0114_quotation_emailed_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual'), ('agent_lpo', 'LPO Agent (Auto)')], default='manual', help_text="'agent_lpo' when emailagent.lpo_agent auto-created this order from an unambiguous LPO-to-quotation match with no human involved -- 'manual' for every other path (the quotation page's Convert button, or a human picking a candidate on the LPO review page). See so.quotation_conversion_service.convert_quotation_to_sales_order.", max_length=20),
        ),
    ]
