# Generated by Django 5.2.3 on 2026-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0115_salesorder_created_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual'), ('agent_lpo', 'LPO Agent (Auto, from Quotation)'), ('agent_lpo_direct', 'LPO Agent (Auto, direct from LPO)')], default='manual', help_text="'agent_lpo' when emailagent.lpo_agent auto-created this order from an unambiguous LPO-to-quotation match with no human involved. 'agent_lpo_direct' when it instead auto-created straight from the LPO's own extracted items with NO quotation at all (see emailagent.lpo_agent.build_sales_order_directly_from_lpo) -- worth knowing apart from 'agent_lpo' since its items/pricing were never vetted via a quotation. 'manual' for every other path (the quotation page's Convert button, or a human picking a candidate on the LPO review page). See so.quotation_conversion_service.convert_quotation_to_sales_order.", max_length=20),
        ),
    ]
