# Generated by Django 5.2.3 on 2026-02-16 12:40

import businesscards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the salesman', max_length=200)),
                ('phone', models.CharField(help_text='Phone number', max_length=50)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('designation', models.CharField(help_text='Job title/designation', max_length=200)),
                ('department', models.CharField(help_text='Department name', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo (optional)', null=True, upload_to=businesscards.models.get_photo_upload_path)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=255, unique=True)),
                ('company_name', models.CharField(default='Company Name', help_text='Company name for branding', max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo (optional)', null=True, upload_to=businesscards.models.get_logo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salesman Card',
                'verbose_name_plural': 'Salesman Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='businesscar_slug_255b43_idx'), models.Index(fields=['email'], name='businesscar_email_1425fc_idx'), models.Index(fields=['department'], name='businesscar_departm_7cac08_idx')],
            },
        ),
    ]
