# Generated by Django 5.2.3 on 2026-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmancard',
            name='qr_background_color',
            field=models.CharField(default='#FFFFFF', help_text='QR code background color (hex code, e.g., #FFFFFF)', max_length=7),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_embed_logo',
            field=models.BooleanField(default=True, help_text='Embed company logo in QR code center'),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_foreground_color',
            field=models.CharField(default='#1B2A4A', help_text='QR code foreground color (hex code, e.g., #1B2A4A)', max_length=7),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_logo_size_percent',
            field=models.IntegerField(default=30, help_text='Logo size as percentage of QR code (10-40%)'),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_size',
            field=models.IntegerField(default=500, help_text='QR code size in pixels (recommended: 500-2000)'),
        ),
    ]
