# Generated by Django 5.2.3 on 2026-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscards', '0002_salesmancard_qr_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmancard',
            name='qr_frame_style',
            field=models.CharField(choices=[('none', 'No Frame'), ('simple', 'Simple Border'), ('rounded', 'Rounded Border'), ('double', 'Double Border'), ('dashed', 'Dashed Border'), ('banner', 'Banner Style'), ('badge', 'Badge Style'), ('card', 'Card Style'), ('modern', 'Modern Frame'), ('classic', 'Classic Frame')], default='none', help_text='Frame style for QR code', max_length=50),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_frame_text',
            field=models.CharField(blank=True, help_text="Optional text to display with frame (e.g., 'Scan Me!')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesmancard',
            name='qr_frame_text_color',
            field=models.CharField(default='#000000', help_text='Color for frame text', max_length=7),
        ),
    ]
