# Generated by Django 5.2.3 on 2026-07-24 12:47

import django.db.models.deletion
import django.utils.timezone
import warranty.models
import warranty.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyLetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('junaid', 'Junaid'), ('alabama', 'Alabama')], max_length=10, unique=True)),
                ('legal_company_name', models.CharField(blank=True, default='', max_length=255)),
                ('ref_no_prefix', models.CharField(blank=True, default='', help_text='e.g. JN/WC or AL/WC — used to build the auto-suggested Ref No.', max_length=30)),
                ('header_logo', models.ImageField(blank=True, help_text='Top-right logo drawn on every page of the generated letter.', null=True, upload_to=warranty.models.warranty_settings_asset_path)),
                ('footer_image', models.ImageField(blank=True, help_text='Full-width footer banner (certification badges + address block) drawn at the bottom of every page. Upload a single ready-made image.', null=True, upload_to=warranty.models.warranty_settings_asset_path)),
                ('default_signatory_name', models.CharField(blank=True, default='', max_length=255)),
                ('default_signatory_title', models.CharField(blank=True, default='', max_length=255)),
                ('default_intro_template', models.TextField(blank=True, default='', help_text="Copied into every new letter's editable Intro Text. Supports {brand} and {iso_standard} placeholders.")),
                ('default_terms_text', models.TextField(blank=True, default='', help_text="Copied into every new letter's editable Terms. One bullet per line.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warranty Letter Settings',
                'verbose_name_plural': 'Warranty Letter Settings',
            },
        ),
        migrations.CreateModel(
            name='WarrantyLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('junaid', 'Junaid'), ('alabama', 'Alabama')], default='junaid', max_length=10)),
                ('ref_no', models.CharField(blank=True, default='', help_text='Auto-suggested per company + year, fully editable.', max_length=50)),
                ('letter_date', models.DateField(default=django.utils.timezone.now)),
                ('project', models.TextField(blank=True, default='')),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('consultant', models.CharField(blank=True, default='', max_length=255)),
                ('main_contractor', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', help_text='Free text — this app is standalone, not tied to submittal brands.', max_length=255)),
                ('iso_standard', models.CharField(blank=True, default='ISO 9001:2015', max_length=100)),
                ('intro_text', models.TextField(blank=True, default='', help_text='Editable intro sentence naming the brand and quality standard.')),
                ('terms_text', models.TextField(blank=True, default='', help_text='Warranty terms — one bullet point per line, any number of lines.')),
                ('signatory_name', models.CharField(blank=True, default='', max_length=255)),
                ('signatory_title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_updated_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='', help_text="Manager's comments left when approving/rejecting.")),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=warranty.models.warranty_signature_path)),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to=warranty.models.warranty_stamp_path)),
                ('generated_pdf', models.FileField(blank=True, help_text='Cached final PDF; regenerated lazily whenever the letter changes.', null=True, storage=warranty.storage_backends.generated_pdf_storage, upload_to=warranty.models.warranty_generated_pdf_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_letters_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_letters_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_letters_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('lpo_no', models.CharField(blank=True, default='', max_length=100)),
                ('brand_model', models.CharField(blank=True, default='', max_length=255)),
                ('total_qty', models.CharField(blank=True, default='', max_length=50)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warranty.warrantyletter')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
