# Generated by Django 5.2.3 on 2026-07-25 05:17

import warranty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyletteritem',
            name='brand_model',
        ),
        migrations.RemoveField(
            model_name='warrantyletteritem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='warrantyletteritem',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='warrantyletteritem',
            name='lpo_no',
        ),
        migrations.RemoveField(
            model_name='warrantyletteritem',
            name='total_qty',
        ),
        migrations.AddField(
            model_name='warrantyletter',
            name='item_columns',
            field=models.JSONField(blank=True, default=warranty.models.default_item_columns, help_text='Ordered item-table columns: [{key, label}, ...]. Freely customizable per letter.'),
        ),
        migrations.AddField(
            model_name='warrantyletteritem',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text="Row values as key-value, keyed by the letter's item_columns keys."),
        ),
    ]
