# Generated by Django 5.2.3 on 2026-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_remove_warrantyletteritem_brand_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyletter',
            name='field_order',
            field=models.JSONField(blank=True, default=list, help_text="Order (and any custom additions) of the project-details block shown on the generated letter: [{'type': 'fixed', 'key': 'project'}, {'type': 'custom', 'label': ..., 'value': ...}, ...]. Empty = default fixed order (project, client, consultant, main_contractor)."),
        ),
    ]
