# Generated by Django 5.2.3 on 2026-07-28 07:19

import warranty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_warrantyletter_field_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantylettersettings',
            name='default_signature_image',
            field=models.ImageField(blank=True, help_text="Auto-attached to every Approved letter's PDF that doesn't have its own signature image (set via the letter's Signature & Stamp panel).", null=True, upload_to=warranty.models.warranty_settings_asset_path),
        ),
        migrations.AddField(
            model_name='warrantylettersettings',
            name='default_stamp_image',
            field=models.ImageField(blank=True, help_text="Auto-attached to every Approved letter's PDF that doesn't have its own stamp image (set via the letter's Signature & Stamp panel).", null=True, upload_to=warranty.models.warranty_settings_asset_path),
        ),
    ]
