# Generated by Django 5.2.3 on 2026-07-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_warrantylettersettings_default_signature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyletter',
            name='terms_text',
            field=models.TextField(blank=True, default='', help_text='Warranty terms as sanitized rich-text HTML (bold/headings/paragraphs/bullet lists).'),
        ),
        migrations.AlterField(
            model_name='warrantylettersettings',
            name='default_terms_text',
            field=models.TextField(blank=True, default='', help_text="Copied into every new letter's editable Terms. Rich text (bold/headings/paragraphs/bullet lists) stored as sanitized HTML."),
        ),
    ]
