# Generated by Django 5.2.3 on 2026-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0005_alter_warrantyletter_terms_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyBrandTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('terms_text', models.TextField(blank=True, default='', help_text='Rich text (bold/headings/paragraphs/bullet lists) stored as sanitized HTML.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warranty Brand Terms',
                'verbose_name_plural': 'Warranty Brand Terms',
            },
        ),
        migrations.RemoveField(
            model_name='warrantylettersettings',
            name='default_terms_text',
        ),
    ]
