# Generated by Django 5.2.3 on 2026-03-12 06:10

import django.db.models.deletion
import submittal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_standard_pdf', models.FileField(blank=True, help_text='Standard index format PDF (Section 2)', null=True, upload_to=submittal.models.company_doc_path)),
                ('company_profile_pdf', models.FileField(blank=True, help_text='Company profile PDF (Section 3)', null=True, upload_to=submittal.models.company_doc_path)),
                ('trade_license_pdf', models.FileField(blank=True, help_text='Trade license PDF (Section 4)', null=True, upload_to=submittal.models.company_doc_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Documents',
                'verbose_name_plural': 'Company Documents',
            },
        ),
        migrations.CreateModel(
            name='ProjectContractorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(blank=True, default='')),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('consultant', models.CharField(blank=True, default='', max_length=255)),
                ('main_contractor', models.CharField(blank=True, default='', max_length=255)),
                ('mep_contractor', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project/Contractor History',
                'verbose_name_plural': 'Project/Contractor History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionDivider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.IntegerField(choices=[(2, 'Index'), (3, 'Company Profile'), (4, 'Trade License'), (5, 'Highlighted Vendor List'), (6, 'Comply Statement'), (7, 'List of Proposed Material'), (8, 'Area of Application'), (9, 'Product Catalogue'), (10, 'Technical Details'), (11, 'Test Certificates'), (12, 'Country of Origin Certificate'), (13, 'Warranty Draft Letter'), (14, 'Previous Approvals')], unique=True)),
                ('section_name', models.CharField(max_length=100)),
                ('divider_pdf', models.FileField(upload_to=submittal.models.section_divider_path)),
            ],
            options={
                'verbose_name': 'Section Divider',
                'ordering': ['section_num'],
            },
        ),
        migrations.CreateModel(
            name='SubmittalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('wras_number', models.CharField(blank=True, default='', help_text='WRAS certification number', max_length=100)),
                ('other_certifications', models.TextField(blank=True, default='', help_text='Other cert numbers, comma-separated')),
                ('catalogue_pdf', models.FileField(blank=True, help_text='Product catalogue PDF (Section 9)', null=True, upload_to=submittal.models.catalogue_upload_path)),
                ('technical_pdf', models.FileField(blank=True, help_text='Technical details PDF (Section 10)', null=True, upload_to=submittal.models.catalogue_upload_path)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(help_text='Project name/description')),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('consultant', models.CharField(blank=True, default='', max_length=255)),
                ('main_contractor', models.CharField(blank=True, default='', max_length=255)),
                ('mep_contractor', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.CharField(blank=True, default='', max_length=255)),
                ('index_format', models.CharField(choices=[('standard', 'Standard Format'), ('client', 'Client Format')], default='standard', max_length=10)),
                ('index_client_pdf', models.FileField(blank=True, help_text='Client-provided index PDF', null=True, upload_to=submittal.models.submittal_upload_path)),
                ('vendor_list_pdf', models.FileField(blank=True, help_text='Highlighted vendor list PDF (optional)', null=True, upload_to=submittal.models.submittal_upload_path)),
                ('comply_statement_file', models.FileField(blank=True, help_text='Comply statement PDF/Word', null=True, upload_to=submittal.models.submittal_upload_path)),
                ('area_of_application_pdf', models.FileField(blank=True, help_text='Area of application PDF (optional)', null=True, upload_to=submittal.models.submittal_upload_path)),
                ('warranty_draft_pdf', models.FileField(blank=True, help_text='Warranty draft letter PDF (placeholder)', null=True, upload_to=submittal.models.submittal_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materials', models.ManyToManyField(blank=True, related_name='submittals', to='submittal.submittalmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('test_certificate', 'Test Certificate'), ('country_of_origin', 'Country of Origin'), ('previous_approval', 'Previous Approval')], max_length=30)),
                ('file', models.FileField(upload_to=submittal.models.material_cert_path)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='submittal.submittalmaterial')),
            ],
            options={
                'ordering': ['material', 'cert_type', 'uploaded_at'],
            },
        ),
    ]
