# Generated by Django 5.2.3 on 2026-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0002_submittalmaterial_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalmaterial',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand (e.g. PEGLER - UK)', max_length=100),
        ),
        migrations.AlterField(
            model_name='submittalmaterial',
            name='model_no',
            field=models.CharField(db_index=True, help_text='Model No. (e.g. 10751, V8850)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submittalmaterial',
            name='size',
            field=models.CharField(blank=True, default='', help_text="Size (e.g. 1/2'' to 2'', 2 1/2 to 12)", max_length=100),
        ),
    ]
