# Generated by Django 5.2.3 on 2026-03-13 09:48

import submittal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0006_submittalsectionupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Final merged PDF; temp uploads are deleted after generation', null=True, upload_to=submittal.models.generated_pdf_path),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was last generated', null=True),
        ),
        migrations.AlterField(
            model_name='submittalsectionupload',
            name='file',
            field=models.FileField(upload_to=submittal.models.section_upload_path),
        ),
    ]
