# Generated by Django 5.2.3 on 2026-03-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0007_alter_submittal_generated_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittalBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('column_definitions', models.JSONField(blank=True, default=list, help_text='[{"key": "model_no", "label": "Model No.", "order": 1}, ...]')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='submittalmaterial',
            options={'ordering': ['display_order', 'model_no']},
        ),
        migrations.AddField(
            model_name='submittal',
            name='materials_columns',
            field=models.JSONField(blank=True, default=list, help_text='Column keys to show in materials table. Empty = show all.'),
        ),
        migrations.RenameField(
            model_name='submittalmaterial',
            old_name='brand',
            new_name='brand_legacy',
        ),
        migrations.AddField(
            model_name='submittalmaterial',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand (e.g. Pegler)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='submittal.submittalbrand'),
        ),
        migrations.AddField(
            model_name='submittalmaterial',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Attribute columns as key-value, e.g. {item_description, material, size, ...}'),
        ),
        migrations.AlterUniqueTogether(
            name='submittalmaterial',
            unique_together={('brand', 'model_no')},
        ),
    ]
