# Generated by Django 5.2.3 on 2026-03-16 05:51

import django.db.models.deletion
from django.db import migrations, models


def ensure_brand_set(apps, schema_editor):
    SubmittalBrand = apps.get_model('submittal', 'SubmittalBrand')
    SubmittalMaterial = apps.get_model('submittal', 'SubmittalMaterial')
    pegler = SubmittalBrand.objects.filter(code='pegler').first()
    if pegler:
        SubmittalMaterial.objects.filter(brand__isnull=True).update(brand=pegler)


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0009_migrate_material_data'),
    ]

    operations = [
        migrations.RunPython(ensure_brand_set, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='area_of_application',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='brand_legacy',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='other_certifications',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='pressure_rating',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='size',
        ),
        migrations.RemoveField(
            model_name='submittalmaterial',
            name='wras_number',
        ),
        migrations.AlterField(
            model_name='submittalmaterial',
            name='brand',
            field=models.ForeignKey(
                help_text='Brand (e.g. Pegler)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='materials',
                to='submittal.submittalbrand',
            ),
        ),
        migrations.AlterField(
            model_name='submittalmaterial',
            name='model_no',
            field=models.CharField(db_index=True, help_text='Model No. (e.g. 10751, V8850)', max_length=100),
        ),
    ]
