# Generated by Django 5.2.3 on 2026-03-16 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0010_remove_legacy_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compliance Option',
                'verbose_name_plural': 'Compliance Options',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='submittal',
            name='compliance_brand',
            field=models.ForeignKey(blank=True, help_text='Brand used for remark options in compliance statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_submittals', to='submittal.submittalbrand'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='compliance_rows',
            field=models.JSONField(blank=True, default=list, help_text='Compliance statement rows: [{specification, compliance, remarks}, ...]'),
        ),
        migrations.CreateModel(
            name='RemarkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(help_text='Remark text (can be multi-line)')),
                ('display_order', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(help_text='Brand this remark belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='remark_options', to='submittal.submittalbrand')),
            ],
            options={
                'verbose_name': 'Remark Option',
                'verbose_name_plural': 'Remark Options',
                'ordering': ['brand', 'display_order', 'label'],
            },
        ),
    ]
