# Generated by Django 5.2.3 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0011_add_compliance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='warranty_date_type',
            field=models.CharField(blank=True, choices=[('toc', 'Date of TOC'), ('invoice', 'Date of Invoice')], default='toc', help_text='Warranty period wording: from date of TOC or Invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='submittal',
            name='warranty_materials_columns',
            field=models.JSONField(blank=True, default=list, help_text='Column keys for warranty materials table. Empty = use materials_columns.'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='warranty_source',
            field=models.CharField(blank=True, choices=[('upload', 'Upload PDF'), ('generate', 'Generate (Pegler-style)')], default='upload', help_text='Use uploaded PDF or generate warranty letter', max_length=20),
        ),
    ]
