# Generated by Django 5.2.3 on 2026-03-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0012_add_warranty_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittal',
            name='warranty_source',
        ),
        migrations.AddField(
            model_name='submittal',
            name='warranty_brand',
            field=models.ForeignKey(blank=True, help_text='Brand with generated warranty format. When set and brand has use_generated_warranty, letter is auto-generated. Otherwise use PDF upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_submittals', to='submittal.submittalbrand'),
        ),
        migrations.AddField(
            model_name='submittalbrand',
            name='use_generated_warranty',
            field=models.BooleanField(default=False, help_text='When enabled, warranty letter is auto-generated from materials table instead of PDF upload. Configure in Admin.'),
        ),
    ]
