# Generated by Django 5.2.3 on 2026-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0014_increase_filefield_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='index_items',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of index entries: [{label, included, display_label?}]. display_label overrides label for this submittal.'),
        ),
    ]
