# Generated by Django 5.2.3 on 2026-06-18 06:22

import submittal.models
import submittal.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0015_alter_submittal_index_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Final merged PDF; stored in Supabase S3. Temp uploads are deleted after generation', null=True, storage=submittal.storage_backends.generated_pdf_storage, upload_to=submittal.models.generated_pdf_path),
        ),
    ]
