# Generated by Django 5.2.3 on 2026-07-09 06:49

import django.db.models.deletion
import submittal.models
import submittal.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0016_alter_submittal_generated_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='title_brand',
            field=models.ForeignKey(blank=True, help_text='Brand shown on the title page. Used to pull brand-level documents (country of origin, authorization letter, previous approvals, previous projects).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_submittals', to='submittal.submittalbrand'),
        ),
        migrations.AlterField(
            model_name='sectiondivider',
            name='section_num',
            field=models.IntegerField(choices=[(2, 'Index'), (3, 'Company Profile'), (4, 'Trade License'), (5, 'Highlighted Vendor List'), (6, 'Comply Statement'), (7, 'List of Proposed Material'), (8, 'Area of Application'), (9, 'Product Catalogue'), (10, 'Technical Details'), (11, 'Test Certificates'), (12, 'Country of Origin Certificate'), (13, 'Warranty Draft Letter'), (14, 'Previous Approvals'), (15, 'Authorization Letter'), (16, 'Previous Projects')], unique=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Final merged PDF; temp uploads are deleted after generation', null=True, storage=submittal.storage_backends.generated_pdf_storage, upload_to=submittal.models.generated_pdf_path),
        ),
        migrations.CreateModel(
            name='BrandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('country_of_origin', 'Country of Origin'), ('authorization_letter', 'Authorization Letter'), ('previous_approval', 'Previous Approval'), ('previous_project', 'Previous Project')], max_length=30)),
                ('file', models.FileField(max_length=255, upload_to=submittal.models.brand_doc_path)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='submittal.submittalbrand')),
            ],
            options={
                'ordering': ['brand', 'doc_type', 'uploaded_at'],
            },
        ),
    ]
