# Generated by Django 5.2.3 on 2026-07-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0017_submittal_title_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittalbrand',
            name='code',
        ),
    ]
