# Generated by Django 5.2.3 on 2026-07-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0019_remarkoption_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remarkoption',
            options={'ordering': ['material', 'brand', 'display_order', 'label'], 'verbose_name': 'Remark Option', 'verbose_name_plural': 'Remark Options'},
        ),
        migrations.AddField(
            model_name='remarkoption',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this remark belongs to (brand-wide brands)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_options', to='submittal.submittalbrand'),
        ),
        migrations.AddField(
            model_name='submittalbrand',
            name='remarks_mode',
            field=models.CharField(choices=[('item', 'Item-wise'), ('brand', 'Brand-wide')], default='item', help_text='Item-wise: remarks are set per material. Brand-wide: one shared remark list for every item under this brand.', max_length=10),
        ),
        migrations.AlterField(
            model_name='remarkoption',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material (item) this remark belongs to (item-wise brands)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_options', to='submittal.submittalmaterial'),
        ),
    ]
