# Generated by Django 5.2.3 on 2026-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0020_alter_remarkoption_options_remarkoption_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittalbrand',
            name='catalogue_mode',
            field=models.CharField(choices=[('item', 'Item-wise'), ('brand', 'Brand-wide')], default='item', help_text='Item-wise: each material has its own Product Catalogue PDF. Brand-wide: one shared Product Catalogue PDF for every item under this brand.', max_length=10),
        ),
        migrations.AddField(
            model_name='submittalbrand',
            name='technical_mode',
            field=models.CharField(choices=[('item', 'Item-wise'), ('brand', 'Brand-wide')], default='item', help_text='Item-wise: each material has its own Technical Details PDF. Brand-wide: one shared Technical Details PDF for every item under this brand.', max_length=10),
        ),
        migrations.AlterField(
            model_name='branddocument',
            name='doc_type',
            field=models.CharField(choices=[('country_of_origin', 'Country of Origin'), ('authorization_letter', 'Authorization Letter'), ('previous_approval', 'Previous Approval'), ('previous_project', 'Previous Project'), ('product_catalogue', 'Product Catalogue'), ('technical_details', 'Technical Details')], max_length=30),
        ),
    ]
