# Generated by Django 5.2.3 on 2026-07-16 05:09

import submittal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0021_submittalbrand_catalogue_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='stamp',
            field=models.ImageField(blank=True, help_text='Company stamp image, stamped onto every page of the generated PDF', null=True, upload_to=submittal.models.submittal_stamp_path),
        ),
    ]
