# Generated by Django 5.2.3 on 2026-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0022_submittal_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittalbrand',
            name='test_cert_mode',
            field=models.CharField(choices=[('item', 'Item-wise'), ('brand', 'Brand-wide')], default='item', help_text='Item-wise: each material has its own Test Certificate(s). Brand-wide: one shared set of Test Certificates for every item under this brand.', max_length=10),
        ),
        migrations.AlterField(
            model_name='branddocument',
            name='doc_type',
            field=models.CharField(choices=[('country_of_origin', 'Country of Origin'), ('authorization_letter', 'Authorization Letter'), ('previous_approval', 'Previous Approval'), ('previous_project', 'Previous Project'), ('product_catalogue', 'Product Catalogue'), ('technical_details', 'Technical Details'), ('test_certificate', 'Test Certificate')], max_length=30),
        ),
    ]
