# Generated by Django 5.2.3 on 2026-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0023_submittalbrand_test_cert_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text="Extra title-page label/value pairs added for this submittal: [{'label': ..., 'value': ...}, ...]"),
        ),
    ]
