# Generated by Django 5.2.3 on 2026-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0024_submittal_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittal',
            name='custom_fields',
        ),
        migrations.AddField(
            model_name='submittal',
            name='field_order',
            field=models.JSONField(blank=True, default=list, help_text="Order (and any custom additions) of the project-details block shown on the title page, compliance statement and materials list: [{'type': 'fixed', 'key': 'project'}, {'type': 'custom', 'label': ..., 'value': ...}, ...]. Empty = default fixed order (project, client, consultant, main_contractor, mep_contractor, brand)."),
        ),
    ]
