# Generated by Django 5.2.3 on 2026-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0025_remove_submittal_custom_fields_submittal_field_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='project',
            field=models.TextField(blank=True, default='', help_text='Project name/description'),
        ),
    ]
