# Generated by Django 5.2.3 on 2026-07-17 12:28

import submittal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0026_alter_submittal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='stamp_mode',
            field=models.CharField(choices=[('all', 'All Pages'), ('custom', 'Custom Pages')], default='all', help_text='Stamp every page, or only the pages listed in stamp_pages.', max_length=10),
        ),
        migrations.AddField(
            model_name='submittal',
            name='stamp_pages',
            field=models.CharField(blank=True, default='', help_text="Comma-separated page numbers/ranges (e.g. '1,3,5-8'), used when stamp_mode is 'custom'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='stamp',
            field=models.ImageField(blank=True, help_text='Company stamp image, stamped onto the generated PDF', null=True, upload_to=submittal.models.submittal_stamp_path),
        ),
    ]
