# Generated by Django 5.2.3 on 2026-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0027_submittal_stamp_mode_submittal_stamp_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittal',
            name='stamp_pages',
        ),
        migrations.AlterField(
            model_name='submittal',
            name='stamp_mode',
            field=models.CharField(choices=[('all', 'All Pages'), ('custom', 'List of Proposed Material & Compliance Statement only')], default='all', help_text='Stamp every page, or only the List of Proposed Material and Comply Statement with Project Specification sections.', max_length=10),
        ),
    ]
