# Generated by Django 5.2.3 on 2026-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0028_remove_submittal_stamp_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittalsectionupload',
            name='page_range',
            field=models.CharField(blank=True, default='', help_text="Optional page range to extract from the uploaded PDF, e.g. '2' or '1,3-5'. Empty = include all pages.", max_length=100),
        ),
    ]
