# Generated by Django 5.2.3 on 2026-07-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0029_submittalsectionupload_page_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='company',
            field=models.CharField(choices=[('junaid', 'Junaid'), ('alabama', 'Alabama')], default='junaid', help_text='Which company letterhead/branding is used on the generated PDF (title page, dividers, materials table, index, compliance statement).', max_length=10),
        ),
    ]
