# Generated by Django 5.2.3 on 2026-07-24 06:19

import submittal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0030_submittal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocuments',
            name='alabama_company_profile_pdf',
            field=models.FileField(blank=True, help_text="Company profile PDF (Section 3) used when the submittal's letterhead is Alabama", null=True, upload_to=submittal.models.company_doc_path),
        ),
        migrations.AddField(
            model_name='companydocuments',
            name='alabama_trade_license_pdf',
            field=models.FileField(blank=True, help_text="Trade license PDF (Section 4) used when the submittal's letterhead is Alabama", null=True, upload_to=submittal.models.company_doc_path),
        ),
    ]
