# Generated by Django 5.2.3 on 2026-08-22 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0114_quotation_emailed_message_id'),
        ('submittal', '0031_companydocuments_alabama_company_profile_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual'), ('agent_email', 'AI Agent (from email)'), ('agent_quotation', 'AI Agent (from quotation)')], db_index=True, default='manual', help_text="Who/what created this submittal -- drives the 'AI Agent' badge/filter on the dashboard and whether Send requires verification first (see status).", max_length=20),
        ),
        migrations.AddField(
            model_name='submittal',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='When the submittal was last sent via the Send Submittal button', null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='emailed_message_id',
            field=models.CharField(blank=True, help_text="Message-ID header of the last 'Send Submittal' email -- lets a reply be matched back to this submittal even if Gmail assigns it a different thread (same fallback used for quotations, see Quotation.emailed_message_id).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='emailed_to',
            field=models.CharField(blank=True, help_text='Comma-separated recipient address(es) the submittal PDF was last emailed to', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='source_quotation',
            field=models.ForeignKey(blank=True, help_text="Set when this submittal was auto-generated from a Quotation's line items (created_via=agent_quotation).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_submittals', to='so.quotation'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('sent', 'Sent')], db_index=True, default='draft', help_text="Agent-created submittals start at 'needs_review' -- a human must open it, correct anything the agent got wrong, and mark it Verified before it can be emailed to a client (see Submittal.send_requires_verification). Manually-built submittals stay 'draft' and can be sent freely, same as before this field existed.", max_length=20),
        ),
        migrations.AddField(
            model_name='submittal',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
