# Generated by Django 5.2.3 on 2026-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0032_submittal_created_via_submittal_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='title_brands',
            field=models.ManyToManyField(blank=True, help_text='All brands selected on the title page. title_brand holds the first one (kept for older records and code that expects a single brand).', related_name='multi_title_submittals', to='submittal.submittalbrand'),
        ),
    ]
