# Generated by Django 5.2.3 on 2026-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0033_submittal_title_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='compliance_rows_by_brand',
            field=models.JSONField(blank=True, default=dict, help_text='Compliance statement rows per brand when several brands are selected on the title page: {"<brand id>": [{specification, compliance, remarks}, ...]}. Empty = the single list in compliance_rows is used.'),
        ),
    ]
