"""
Django settings for salesorder project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a&fnmzpzlc4s5x_js&b4)umepe6&@(1+()eu=f))3!hyhw&r7='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'so',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'tradelicense',
    'businesscards',
    'alabama',
    'submittal',
    'warranty',
    'emailagent',

    'django.contrib.humanize',
    
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    # CORS MUST ALWAYS BE FIRST
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # MUST COME BEFORE DEVICE TRACKER
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # ✅ YOUR DEVICE TRACKER HERE
    'so.device_middleware.DeviceRestrictionMiddleware',

    'so.middleware.DeviceTrackingMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # Development only!

ROOT_URLCONF = 'salesorder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'alabama.context_processors.alabama_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'salesorder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}
VPS_API_KEY = 'rLEkUZQiljwQWPS5ZJ8m6zawpsr9QUvRqYka-hj7fBw'  # Or your own secret key

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = "Asia/Dubai"


TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CREATE_CHAT_ID = os.getenv('TELEGRAM_CREATE_CHAT_ID', '')
TELEGRAM_APPROVE_CHAT_ID = os.getenv('TELEGRAM_APPROVE_CHAT_ID', '')
# MD Approvals: separate Telegram bot/group (different from salesorder create/approve)
TELEGRAM_MD_APPROVAL_BOT_TOKEN = os.getenv('TELEGRAM_MD_APPROVAL_BOT_TOKEN', '')  # Bot for MD Approvals group
TELEGRAM_MD_APPROVAL_CHAT_ID = os.getenv('TELEGRAM_MD_APPROVAL_CHAT_ID', '')  # "MD Approvals" group chat ID

WHATSAPP_API_VERSION = os.getenv('WHATSAPP_API_VERSION', 'v22.0')  # Or your preferred, active version
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')

# SAP API Configuration
# On VPS with SSH tunnel: set SAP_API_BASE_HOST=http://localhost:8443
SAP_API_BASE_HOST = os.getenv('SAP_API_BASE_HOST', 'http://192.168.1.103')
SAP_API_BASE_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/SalesOrder"
SAP_QUOTATION_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/SalesQuotations"
SAP_PURCHASE_ORDER_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/PurchaseOrder"
SAP_AR_INVOICE_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/ARInvoice"
SAP_AR_CREDIT_MEMO_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/ARCreditMemo"
SAP_FINANCE_SUMMARY_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/FinanceSummary"
SAP_GET_PAYMENT_DETAILS_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/GetPaymentDetails"
SAP_API_TIMEOUT = 30
SAP_SYNC_DAYS_BACK = 3  # Default: fetch new orders + last 3 days = 4 days total
# Optional: SAP_SYNC_FROM_DATE / SAP_SYNC_TO_DATE (YYYY-MM-DD) - used when From/To date range selected in Settings sync

# VPS API Configuration (for PC script to send data to VPS)
VPS_BASE_URL = os.getenv('VPS_BASE_URL', 'https://salesorder.junaidworld.com')  # Production VPS URL
VPS_API_KEY = os.getenv('VPS_API_KEY', 'test')  # Must match between PC script and VPS

# ── Email Tracking & Classification Agent (Gmail + Claude) ──────────────
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GMAIL_REFRESH_TOKEN = os.getenv('GMAIL_REFRESH_TOKEN', '')
GMAIL_TOKEN_URI = 'https://oauth2.googleapis.com/token'
GMAIL_SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

# Real-time push notifications (Gmail -> Google Cloud Pub/Sub -> our webhook)
# instead of waiting for the next scheduled poll_gmail run. Set up via:
#   python manage.py watch_gmail
# GMAIL_PUBSUB_TOPIC: full topic name, e.g. projects/<gcp-project-id>/topics/gmail-inbox
# GMAIL_PUSH_TOKEN: shared secret appended to the webhook URL as ?token=...
#   so only our own Pub/Sub subscription can trigger it.
GMAIL_PUBSUB_TOPIC = os.getenv('GMAIL_PUBSUB_TOPIC', '')
GMAIL_PUSH_TOKEN = os.getenv('GMAIL_PUSH_TOKEN', '')

# Second inbound source for the same agent -- a plain IMAP mailbox (e.g.
# sales@junaid.ae), polled the same way as Gmail via poll_outlook (see
# emailagent/outlook_client.py + management/commands/poll_outlook.py).
OUTLOOK_IMAP_HOST = os.getenv('OUTLOOK_IMAP_HOST', '')
OUTLOOK_IMAP_PORT = int(os.getenv('OUTLOOK_IMAP_PORT', '993'))
OUTLOOK_IMAP_USER = os.getenv('OUTLOOK_IMAP_USER', '')
OUTLOOK_IMAP_PASSWORD = os.getenv('OUTLOOK_IMAP_PASSWORD', '')
OUTLOOK_IMAP_FOLDER = os.getenv('OUTLOOK_IMAP_FOLDER', 'INBOX')

# Third inbound source, same agent -- another plain IMAP mailbox
# (project@junaid.ae), SUBMITTAL-ONLY: classified the same as any other
# mailbox, but emailagent.services.process_new_message never runs quotation
# drafting or LPO processing for mail from this source, regardless of what
# it classifies as (see poll_project_mailbox / the submittal_only param).
# Host/port/folder default to the same values as the primary OUTLOOK_IMAP_*
# mailbox since it's on the same hosting -- only the mailbox user/password
# genuinely differ; override PROJECT_IMAP_HOST/PORT/FOLDER in .env if that
# ever isn't true.
PROJECT_IMAP_HOST = os.getenv('PROJECT_IMAP_HOST', OUTLOOK_IMAP_HOST)
PROJECT_IMAP_PORT = int(os.getenv('PROJECT_IMAP_PORT', str(OUTLOOK_IMAP_PORT)))
PROJECT_IMAP_USER = os.getenv('PROJECT_IMAP_USER', '')
PROJECT_IMAP_PASSWORD = os.getenv('PROJECT_IMAP_PASSWORD', '')
PROJECT_IMAP_FOLDER = os.getenv('PROJECT_IMAP_FOLDER', OUTLOOK_IMAP_FOLDER)

# Fourth inbound source, same agent -- another plain IMAP mailbox,
# SUBMITTAL-ONLY same as PROJECT_IMAP_* above (see poll_submittal_mailbox /
# the submittal_only param). Host/port/folder default to the primary
# OUTLOOK_IMAP_* mailbox's values; override in .env if this mailbox is
# hosted elsewhere.
SUBMITTAL_IMAP_HOST = os.getenv('SUBMITTAL_IMAP_HOST', OUTLOOK_IMAP_HOST)
SUBMITTAL_IMAP_PORT = int(os.getenv('SUBMITTAL_IMAP_PORT', str(OUTLOOK_IMAP_PORT)))
SUBMITTAL_IMAP_USER = os.getenv('SUBMITTAL_IMAP_USER', '')
SUBMITTAL_IMAP_PASSWORD = os.getenv('SUBMITTAL_IMAP_PASSWORD', '')
SUBMITTAL_IMAP_FOLDER = os.getenv('SUBMITTAL_IMAP_FOLDER', OUTLOOK_IMAP_FOLDER)

# Outbound email (quotation "Send to Client" button) -- separate from the
# GMAIL_* OAuth creds above, which are read-only and used only for the
# inbound email-tracking agent. Sending uses plain SMTP with a Gmail App
# Password (myaccount.google.com/apppasswords), configured in .env:
#   EMAIL_HOST_USER=you@gmail.com
#   EMAIL_HOST_PASSWORD=<16-char app password>
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
EMAILAGENT_CLASSIFICATION_MODEL = os.getenv('EMAILAGENT_CLASSIFICATION_MODEL', 'claude-sonnet-5')
# Cheap/fast model used only for the triage pre-check in classify_email --
# decides whether an email is obviously simple (no attachments, nothing to
# extract) before spending EMAILAGENT_CLASSIFICATION_MODEL on it.
EMAILAGENT_TRIAGE_MODEL = os.getenv('EMAILAGENT_TRIAGE_MODEL', 'claude-haiku-4-5-20251001')
EMAILAGENT_CONFIDENCE_THRESHOLD = float(os.getenv('EMAILAGENT_CONFIDENCE_THRESHOLD', '0.75'))

# The 'poll_gmail' management command wires its own file handler at module
# import time, so manual runs already log to logs/poll_gmail.log. The
# Pub/Sub webhook (emailagent/views.py:gmail_push_webhook) instead calls
# services.poll_gmail() directly from a background thread, whose loggers
# (emailagent.services, emailagent.gmail_client, ...) had no handler at all
# -- push-triggered runs were completing (or failing) with zero record
# anywhere. This routes all emailagent.* logging to its own file too.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'emailagent': {
            'format': '%(asctime)s | %(levelname)-8s | %(name)s | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'emailagent_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'emailagent.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'emailagent',
        },
    },
    'loggers': {
        'emailagent': {
            'handlers': ['emailagent_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
EMAILAGENT_MAX_ATTACHMENT_IMAGES = int(os.getenv('EMAILAGENT_MAX_ATTACHMENT_IMAGES', '10'))
EMAILAGENT_MAX_ATTACHMENT_MB = int(os.getenv('EMAILAGENT_MAX_ATTACHMENT_MB', '20'))
EMAILAGENT_AGENT_MAX_ITERATIONS = int(os.getenv('EMAILAGENT_AGENT_MAX_ITERATIONS', '6'))
# Per-request bound on every Claude call the agent makes (classification,
# quotation drafting, etc.) -- with no timeout set, the SDK's own default can
# leave a single unusually large/slow request (e.g. an email with 10+ image
# attachments) hanging far longer than is reasonable for an unattended
# pipeline, silently blocking every message queued behind it.
EMAILAGENT_CLAUDE_TIMEOUT_SECS = int(os.getenv('EMAILAGENT_CLAUDE_TIMEOUT_SECS', '180'))

# Agent Activity dashboard (emailagent:agent_activity) -- tune these as
# AgentRun volume grows, no code changes needed:
#   PAGE_SIZE   how many rows (log view) / enquiries (by-enquiry view) per page
#   MAX_ROWS    hard cap on rows pulled into the by-enquiry grouping pass --
#               keeps that view fast regardless of total AgentRun table size;
#               narrow the date-range filter on the page itself to see further back
EMAILAGENT_ACTIVITY_PAGE_SIZE = int(os.getenv('EMAILAGENT_ACTIVITY_PAGE_SIZE', '20'))
EMAILAGENT_ACTIVITY_MAX_ROWS = int(os.getenv('EMAILAGENT_ACTIVITY_MAX_ROWS', '2000'))

# LPO agent (emailagent/lpo_agent.py) matching thresholds -- see its
# find_matching_quotation() docstring for how these are used. Neither one
# ever gates auto-CREATION of a Sales Order (only an exact, unique
# quotation-number match does that); they only control which candidate
# quotations get surfaced to a human on the "needs review" page.
EMAILAGENT_LPO_FUZZY_MATCH_THRESHOLD = float(os.getenv('EMAILAGENT_LPO_FUZZY_MATCH_THRESHOLD', '0.8'))
EMAILAGENT_LPO_MATCH_LOOKBACK_DAYS = int(os.getenv('EMAILAGENT_LPO_MATCH_LOOKBACK_DAYS', '180'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── Supabase S3 (generated submittal PDFs) ──────────────────────────────
# Only the final generated PDF is stored here; all other media stays local.
AWS_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('S3_REGION')
AWS_S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL')
