"""
Django settings for salesorder project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a&fnmzpzlc4s5x_js&b4)umepe6&@(1+()eu=f))3!hyhw&r7='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'so',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'tradelicense',
    'businesscards',

    'django.contrib.humanize',
    
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    # CORS MUST ALWAYS BE FIRST
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # MUST COME BEFORE DEVICE TRACKER
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # ✅ YOUR DEVICE TRACKER HERE
    'so.device_middleware.DeviceRestrictionMiddleware',

    'so.middleware.DeviceTrackingMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # Development only!

ROOT_URLCONF = 'salesorder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salesorder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}
VPS_API_KEY = 'rLEkUZQiljwQWPS5ZJ8m6zawpsr9QUvRqYka-hj7fBw'  # Or your own secret key

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = "Asia/Dubai"


TELEGRAM_BOT_TOKEN = "8282988077:AAFFFqgRMejQbfWCi843wUc9dCNu-GLzZn4"
TELEGRAM_CREATE_CHAT_ID = "-4928205676"
TELEGRAM_APPROVE_CHAT_ID = "-4900133568"

WHATSAPP_API_VERSION = 'v22.0' # Or your preferred, active version
WHATSAPP_ACCESS_TOKEN = 'EAAQptligo50BPxZCBoRIIoopsfBzTeTBZCOrc1XGa9xC0tGikkpp5ajjM1inCFemKZCtAiRnpWWzZB1kJq6WqgMwL7RZC8MqHynBShSCM7Y3mpm7HfKOhbyTvNCqy5A6QwK43NVfENklGeHFYEAhRVh8aljVeNkPDOGfWZChs6ytvctfBKPZCtlNgA41ZCvDqZB0t'
WHATSAPP_PHONE_NUMBER_ID = '623707730818076'

# SAP API Configuration
# On VPS with SSH tunnel: set SAP_API_BASE_HOST=http://localhost:8443
SAP_API_BASE_HOST = os.getenv('SAP_API_BASE_HOST', 'http://192.168.1.103')
SAP_API_BASE_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/SalesOrder"
SAP_QUOTATION_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/SalesQuotations"
SAP_PURCHASE_ORDER_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/PurchaseOrder"
SAP_AR_INVOICE_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/ARInvoice"
SAP_AR_CREDIT_MEMO_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/ARCreditMemo"
SAP_FINANCE_SUMMARY_API_URL = f"{SAP_API_BASE_HOST}/IntegrationApi/api/FinanceSummary"
SAP_API_TIMEOUT = 30
SAP_SYNC_DAYS_BACK = 3  # Default: fetch new orderc+ 3 days = 4 days total)

# VPS API Configuration (for PC script to send data to VPS)
VPS_BASE_URL = os.getenv('VPS_BASE_URL', 'https://salesorder.junaidworld.com')  # Production VPS URL
VPS_API_KEY = os.getenv('VPS_API_KEY', 'test')  # Must match between PC script and VPS



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')