# Generated by Django 5.2.3 on 2026-02-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('so', '0086_add_proposed_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit Memo', 'Credit Memo')], max_length=20)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('posting_date', models.DateField(db_index=True)),
                ('sales_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabama_sales_lines', to='so.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabama_sales_lines', to='so.items')),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'document_number'], name='alabama_ala_documen_054854_idx'), models.Index(fields=['posting_date'], name='alabama_ala_posting_26a9e4_idx')],
            },
        ),
    ]
