# Generated by Django 5.2.3 on 2026-02-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaSAPQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('posting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('salesman_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('bp_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_to', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='alabama_ala_posting_22e492_idx'), models.Index(fields=['salesman_name'], name='alabama_ala_salesma_3851a4_idx'), models.Index(fields=['status'], name='alabama_ala_status_a478b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlabamaSAPQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alabama.alabamasapquotation')),
            ],
        ),
    ]
