# Generated by Django 5.2.3 on 2026-02-28 06:35

from django.db import migrations, models


def seed_salesman_mappings(apps, schema_editor):
    AlabamaSalesmanMapping = apps.get_model('alabama', 'AlabamaSalesmanMapping')
    mappings = [
        ('a.kader', 'KADER'),
        ('a. kader', 'KADER'),
        ('a.kadar', 'KADER'),
        ('a. kadar', 'KADER'),
        ('a.musharaf', 'MUSHARAF'),
        ('a. musharaf', 'MUSHARAF'),
    ]
    for raw, norm in mappings:
        AlabamaSalesmanMapping.objects.get_or_create(raw_name=raw, defaults={'normalized_name': norm})


def reverse_seed(apps, schema_editor):
    pass  # No-op; table is dropped on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0002_alabamasapquotation_alabamasapquotationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaSalesmanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(help_text='Variant from Excel, e.g. A.KADER, A. KADER', max_length=255)),
                ('normalized_name', models.CharField(help_text='Canonical name, e.g. KADER', max_length=255)),
            ],
            options={
                'ordering': ['raw_name'],
            },
        ),
        migrations.RunPython(seed_salesman_mappings, reverse_seed),
    ]
