# Generated by Django 5.2.3 on 2026-02-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0003_add_salesman_mapping'),
        ('so', '0088_set_alabama_users_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaDeliveryOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(db_index=True, help_text='DO number', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('sales_person', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('lpo', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabama_delivery_order_lines', to='so.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabama_delivery_order_lines', to='so.items')),
            ],
            options={
                'indexes': [models.Index(fields=['do_number'], name='alabama_ala_do_numb_10e058_idx'), models.Index(fields=['date'], name='alabama_ala_date_b0bcb5_idx'), models.Index(fields=['sales_person'], name='alabama_ala_sales_p_5f9f18_idx')],
            },
        ),
    ]
