# Generated by Django 5.2.3 on 2026-03-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0006_alabamadeliveryorder_indexes'),
        ('so', '0088_set_alabama_users_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(db_index=True, max_length=100)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('posting_date', models.DateField(db_index=True)),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('sales_employee', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.CharField(blank=True, max_length=500, null=True)),
                ('item_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='alabamadeliveryorder',
            new_name='alabama_ala_date_f7b86c_idx',
            old_name='alabama_ala_date_idx',
        ),
        migrations.RenameIndex(
            model_name='alabamadeliveryorder',
            new_name='alabama_ala_sales_p_6024cc_idx',
            old_name='alabama_ala_sales_p_idx',
        ),
        migrations.AddField(
            model_name='alabamapurchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alabama_purchase_lines', to='so.items'),
        ),
        migrations.AddIndex(
            model_name='alabamapurchaseline',
            index=models.Index(fields=['document_type', 'document_number'], name='alabama_ala_documen_b5d04f_idx'),
        ),
        migrations.AddIndex(
            model_name='alabamapurchaseline',
            index=models.Index(fields=['posting_date'], name='alabama_ala_posting_161ec1_idx'),
        ),
    ]
