# Generated by Django 5.2.3 on 2026-03-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0007_add_purchase_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('posting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('salesman_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bp_reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('row_total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='alabama_ala_posting_85df3a_idx'), models.Index(fields=['salesman_name'], name='alabama_ala_salesma_a28df7_idx'), models.Index(fields=['customer_name'], name='alabama_ala_custome_97ec7b_idx'), models.Index(fields=['status'], name='alabama_ala_status_175cbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlabamaSalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1)),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('row_status', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('remaining_open_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salesorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alabama.alabamasalesorder')),
            ],
            options={
                'indexes': [models.Index(fields=['salesorder', 'line_no'], name='alabama_ala_salesor_a3e8ed_idx'), models.Index(fields=['item_no'], name='alabama_ala_item_no_f073b7_idx'), models.Index(fields=['row_status'], name='alabama_ala_row_sta_c4c91c_idx')],
            },
        ),
    ]
