# Generated by Django 5.2.3 on 2026-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabama', '0008_alabamasalesorder_alabamasalesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='alabamasalesorder',
            name='management_remarks',
            field=models.TextField(blank=True, help_text='Internal management remarks; optional Telegram to salesman', null=True),
        ),
        migrations.AlterField(
            model_name='alabamasalesorder',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks from SAP / Excel upload (not editable as management remarks)', null=True),
        ),
    ]
